# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(max_length=50, unique=True)),
                ('reason', models.TextField()),
                ('clinical_summary', models.TextField()),
                ('required_service', models.CharField(default='Specialist Evaluation', max_length=100)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine Referral'), ('URGENT', 'Urgent Evaluation'), ('EMERGENCY', 'Emergency Referral')], default='ROUTINE', max_length=20)),
                ('referral_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('ACCEPTED', 'Accepted by Hospital'), ('IN_TRANSIT', 'Patient in Transit'), ('REACHED', 'Reached Facility'), ('UNDER_TREATMENT', 'Under Treatment'), ('FOLLOW_UP_PENDING', 'Follow-up Pending'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='CREATED', max_length=30)),
                ('destination_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_referrals', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient')),
                ('referring_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_referrals', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='NCD', max_length=30)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DUE_TODAY', 'Due Today'), ('OVERDUE', 'Overdue'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='patients.patient')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.visit')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='referrals.referral')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_findings', models.TextField()),
                ('treatment_summary', models.TextField()),
                ('return_advice', models.TextField()),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('hospital_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referral', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='referrals.referral')),
            ],
        ),
    ]
