# Generated by Django 4.2.30 on 2026-09-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_prescriptionitem_medicine'),
        ('visits', '0002_visitstatushistory_alter_token_options_and_more'),
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='referral',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='visits.visit'),
        ),
    ]
