# Generated by Django 4.2.30 on 2026-09-23 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_person'),
        ('visits', '0004_facilitydailycounter'),
        ('facilities', '0003_servicemaster_facilityservice_department'),
        ('accounts', '0003_person_rolemaster_staffprofile_staffroleassignment_and_more'),
        ('referrals', '0003_populate_referral_encounter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_number', models.CharField(max_length=50, unique=True)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='ROUTINE', max_length=20)),
                ('reason', models.TextField()),
                ('clinical_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('ACKNOWLEDGED', 'Acknowledged'), ('IN_TRANSIT', 'In Transit'), ('ARRIVED', 'Arrived'), ('UNDER_SPECIALIST_CARE', 'Under Specialist Care'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='INITIATED', max_length=30)),
                ('referral_date', models.DateField(default=datetime.date.today)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='incoming_referral_orders', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referral_orders', to='patients.patient')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='authored_referral_orders', to='accounts.staffprofile')),
                ('source_facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='outgoing_referral_orders', to='facilities.facility')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referral_orders', to='visits.visit')),
            ],
            options={
                'db_table': 'referral_orders',
            },
        ),
        migrations.CreateModel(
            name='ReferralEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ACKNOWLEDGED', 'Acknowledged'), ('TRIAGED', 'Triaged'), ('SPECIALIST_CONSULT', 'Specialist Consult'), ('ADMITTED', 'Admitted'), ('COUNTER_REFERRAL_DISCHARGE', 'Counter Referral Discharge'), ('CANCELLED', 'Cancelled')], max_length=30)),
                ('specialist_findings', models.TextField(blank=True, default='')),
                ('treatment_rendered', models.TextField(blank=True, default='')),
                ('return_advice', models.TextField(blank=True, default='')),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('recorded_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='recorded_referral_events', to='accounts.staffprofile')),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='referrals.referralorder')),
            ],
            options={
                'db_table': 'referral_events',
            },
        ),
        migrations.CreateModel(
            name='FollowUpTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('category', models.CharField(choices=[('NCD_ROUTINE', 'NCD Routine'), ('POST_REFERRAL', 'Post Referral'), ('LAB_REVIEW', 'Lab Review'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('MISSED', 'Missed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('clinical_instructions', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='completed_follow_ups', to='accounts.staffprofile')),
                ('completed_in_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='completed_follow_ups', to='visits.visit')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='follow_up_tasks', to='facilities.facility')),
                ('originating_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='originating_follow_ups', to='visits.visit')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='follow_up_tasks', to='patients.patient')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='follow_up_tasks', to='referrals.referralorder')),
            ],
            options={
                'db_table': 'follow_up_tasks',
            },
        ),
        migrations.AddConstraint(
            model_name='followuptask',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('completed_at__isnull', False), ('completed_by_staff__isnull', False), ('completed_in_visit__isnull', False), ('status', 'COMPLETED')), models.Q(('status', 'COMPLETED'), _negated=True), _connector='OR'), name='chk_followup_completion_integrity'),
        ),
    ]
