# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomedicalWasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('yellow_bag_kg', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('red_bag_kg', models.DecimalField(decimal_places=2, default=1.8, max_digits=5)),
                ('white_translucent_sharp_kg', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('blue_box_glass_kg', models.DecimalField(decimal_places=2, default=1.2, max_digits=5)),
                ('disposal_agency', models.CharField(default='Authorized CBWTF Vendor', max_length=150)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('handed_over_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QualityChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(auto_now_add=True)),
                ('cleanliness_score', models.IntegerField(default=95)),
                ('infection_control_passed', models.BooleanField(default=True)),
                ('kayakalpa_audit_status', models.CharField(default='COMPLIANT', max_length=50)),
                ('corrective_actions', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('inspected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
