# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure_systolic', models.IntegerField(default=120)),
                ('blood_pressure_diastolic', models.IntegerField(default=80)),
                ('pulse_bpm', models.IntegerField(default=72)),
                ('temperature_f', models.DecimalField(decimal_places=1, default=98.6, max_digits=4)),
                ('spo2_percent', models.IntegerField(default=98)),
                ('respiratory_rate', models.IntegerField(default=18)),
                ('height_cm', models.DecimalField(decimal_places=1, default=165.0, max_digits=5)),
                ('weight_kg', models.DecimalField(decimal_places=1, default=65.0, max_digits=5)),
                ('bmi', models.DecimalField(decimal_places=1, default=23.8, max_digits=4)),
                ('blood_glucose_mgdl', models.IntegerField(default=110)),
                ('high_bp_flag', models.BooleanField(default=False)),
                ('high_glucose_flag', models.BooleanField(default=False)),
                ('fever_flag', models.BooleanField(default=False)),
                ('low_spo2_flag', models.BooleanField(default=False)),
                ('pregnancy_high_risk_flag', models.BooleanField(default=False)),
                ('emergency_flag', models.BooleanField(default=False)),
                ('ncd_risk_flag', models.BooleanField(default=False)),
                ('nurse_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nurse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage', to='visits.visit')),
            ],
        ),
    ]
