# Generated by Django 4.2.30 on 2026-09-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_facilitydailycounter'),
        ('accounts', '0003_person_rolemaster_staffprofile_staffroleassignment_and_more'),
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Triage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('pulse_rate', models.IntegerField(blank=True, null=True)),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('spo2_percentage', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('triaged_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='triages', to='accounts.staffprofile')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_observation', to='visits.visit')),
            ],
            options={
                'db_table': 'triages',
            },
        ),
        migrations.AddConstraint(
            model_name='triage',
            constraint=models.CheckConstraint(check=models.Q(('systolic_bp__isnull', True), ('systolic_bp__range', (40, 300)), _connector='OR'), name='chk_triages_bp_sys'),
        ),
        migrations.AddConstraint(
            model_name='triage',
            constraint=models.CheckConstraint(check=models.Q(('diastolic_bp__isnull', True), ('diastolic_bp__range', (30, 200)), _connector='OR'), name='chk_triages_bp_dia'),
        ),
        migrations.AddConstraint(
            model_name='triage',
            constraint=models.CheckConstraint(check=models.Q(('spo2_percentage__isnull', True), ('spo2_percentage__range', (50, 100)), _connector='OR'), name='chk_triages_spo2'),
        ),
        migrations.AddConstraint(
            model_name='triage',
            constraint=models.CheckConstraint(check=models.Q(('pulse_rate__isnull', True), ('pulse_rate__range', (30, 250)), _connector='OR'), name='chk_triages_pulse'),
        ),
    ]
