# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_code', models.CharField(max_length=50, unique=True)),
                ('facility_name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(choices=[('MAIN_HOSPITAL', 'Main Hospital'), ('REFERRAL_HOSPITAL', 'Referral Hospital'), ('SECONDARY_HOSPITAL', 'Secondary Hospital'), ('UPHC', 'Urban Primary Health Centre (UPHC)'), ('NAMMA_CLINIC', 'Namma Clinic (Urban HWC)'), ('URBAN_CLINIC', 'Urban Clinic'), ('RURAL_CLINIC', 'Rural Clinic'), ('VILLAGE_CLINIC', 'Village Clinic'), ('DIAGNOSTIC_CENTER', 'Diagnostic Center'), ('OTHER', 'Other Health Facility')], default='NAMMA_CLINIC', max_length=30)),
                ('city_or_ulb', models.CharField(default='BBMP', max_length=100)),
                ('urban_rural', models.CharField(choices=[('URBAN', 'Urban'), ('RURAL', 'Rural')], default='URBAN', max_length=10)),
                ('address', models.TextField(blank=True)),
                ('latitude', models.DecimalField(decimal_places=6, default=12.9716, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, default=77.5946, max_digits=10)),
                ('population_served', models.IntegerField(default=20000)),
                ('vulnerable_population', models.IntegerField(default=5000)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('opening_time', models.CharField(default='09:00 AM', max_length=20)),
                ('closing_time', models.CharField(default='04:30 PM', max_length=20)),
                ('emergency_available', models.BooleanField(default=False)),
                ('lab_available', models.BooleanField(default=True)),
                ('pharmacy_available', models.BooleanField(default=True)),
                ('teleconsultation_available', models.BooleanField(default=True)),
                ('bed_capacity', models.IntegerField(default=0)),
                ('services', models.TextField(default='General OPD, NCD Screening, ANC/PNC Care, Immunization, Basic Diagnostics, Pharmacy')),
                ('specialists', models.TextField(default='General Physician, Staff Nurse, Lab Tech, Pharmacist')),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='geography.district')),
                ('parent_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='facilities.facility')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='geography.state')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='geography.ward')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='geography.zone')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('PARENT', 'Parent Organization'), ('REFERRAL', 'Routine Referral'), ('SPECIALIST', 'Specialist Referral'), ('EMERGENCY', 'Emergency Referral'), ('DIAGNOSTIC', 'Diagnostic Referral'), ('SUPPORT', 'Operational Support'), ('TELECONSULTATION', 'Teleconsultation Hub')], default='REFERRAL', max_length=30)),
                ('service', models.CharField(default='General Referral', max_length=100)),
                ('priority', models.CharField(default='PRIMARY', max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='facilities.facility')),
                ('source_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='facilities.facility')),
            ],
        ),
    ]
