# Generated by Django 6.1.1 on 2026-09-04 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityBedAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_number', models.CharField(max_length=30)),
                ('bed_category', models.CharField(choices=[('GENERAL_OBSERVATION', 'General OPD Observation Bed'), ('EMERGENCY_TRIAGE', 'Emergency Triage & Resuscitation Bed'), ('OXYGEN_SUPPORTED', 'Oxygen Supported High-Care Bed'), ('DAY_CARE_ISOLATION', 'Day-Care & Isolation Ward Bed')], default='GENERAL_OBSERVATION', max_length=30)),
                ('patient_name', models.CharField(blank=True, max_length=150)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('attending_doctor', models.CharField(default='Dr. Medical Officer', max_length=100)),
                ('status', models.CharField(default='OCCUPIED', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_allocations', to='facilities.facility')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bed_allocations', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityBedCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed_category', models.CharField(choices=[('GENERAL_OBSERVATION', 'General OPD Observation Bed'), ('EMERGENCY_TRIAGE', 'Emergency Triage & Resuscitation Bed'), ('OXYGEN_SUPPORTED', 'Oxygen Supported High-Care Bed'), ('DAY_CARE_ISOLATION', 'Day-Care & Isolation Ward Bed')], default='GENERAL_OBSERVATION', max_length=30)),
                ('total_beds', models.IntegerField(default=6)),
                ('occupied_beds', models.IntegerField(default=2)),
                ('cleaning_in_progress', models.IntegerField(default=1)),
                ('under_maintenance', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='Observation ward equipped with monitor & IV stands.')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_capacities', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityConsumableInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('CLEANING_SANITATION', 'Floor Cleaning & Disinfectants'), ('INFECTION_CONTROL', 'Infection Control & Biohazard'), ('PERSONAL_PROTECTION', 'Personal Protective Equipment (PPE)'), ('GENERAL_FACILITY', 'General Facility Supplies')], default='CLEANING_SANITATION', max_length=30)),
                ('unit_of_measure', models.CharField(default='Litres', max_length=30)),
                ('current_stock', models.IntegerField(default=50)),
                ('min_threshold', models.IntegerField(default=15)),
                ('reorder_status', models.CharField(default='ADEQUATE', max_length=20)),
                ('last_restocked', models.DateField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumable_inventory', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityMaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('ELECTRICAL', 'Electrical & Wiring Maintenance'), ('PLUMBING', 'Plumbing & Water Supply'), ('OXYGEN_SYSTEM', 'Oxygen Manifold & Tubing'), ('SOLAR_UPS', 'Solar Power & UPS Battery Backup'), ('MEDICAL_EQUIPMENT', 'Medical Equipment Repair'), ('SANITY_CLEANING', 'Facility Cleaning & Deep Sanitation'), ('BUILDING_STRUCTURE', 'Building & Structural Repair')], default='ELECTRICAL', max_length=30)),
                ('equipment_or_area', models.CharField(max_length=150)),
                ('priority', models.CharField(choices=[('LOW', 'Low Priority'), ('MEDIUM', 'Medium Priority'), ('HIGH', 'High Priority'), ('EMERGENCY', 'Emergency Work Order')], default='MEDIUM', max_length=20)),
                ('description', models.TextField()),
                ('reported_by', models.CharField(default='Staff Nurse', max_length=100)),
                ('assigned_technician', models.CharField(default='BBMP Electrical Division Team', max_length=100)),
                ('status', models.CharField(choices=[('LOGGED', 'Logged & Pending'), ('ASSIGNED', 'Assigned to Technician'), ('IN_PROGRESS', 'Work in Progress'), ('RESOLVED', 'Resolved & Tested'), ('CLOSED', 'Ticket Closed')], default='LOGGED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityOxygenSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oxygen_source', models.CharField(choices=[('CYLINDER_MANIFOLD', 'B/D Type Cylinder Manifold'), ('CONCENTRATOR', 'Medical Oxygen Concentrator'), ('PSA_PLANT', 'On-Site PSA Oxygen Plant'), ('LIQUID_TANK', 'Liquid Medical Oxygen (LMO) Tank')], default='CYLINDER_MANIFOLD', max_length=30)),
                ('total_cylinders', models.IntegerField(default=10)),
                ('active_cylinders', models.IntegerField(default=7)),
                ('empty_cylinders', models.IntegerField(default=3)),
                ('current_pressure_psi', models.IntegerField(default=1850)),
                ('fill_percentage', models.IntegerField(default=85)),
                ('status', models.CharField(choices=[('OPTIMAL', 'Optimal Supply (>75%)'), ('ADEQUATE', 'Adequate Supply (50-75%)'), ('REFILL_REQUIRED', 'Refill Required (<50%)'), ('CRITICAL_LOW', 'Critical Low Stock (<25%)')], default='OPTIMAL', max_length=30)),
                ('last_inspected', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='Primary oxygen manifold operational and pressure tested.')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oxygen_supplies', to='facilities.facility')),
            ],
        ),
    ]
