# Generated by Django 6.1.1 on 2026-10-06 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasecase',
            name='report_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
    ]
