# Generated by Django 4.2.30 on 2026-09-23 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_taluk'),
        ('facilities', '0003_servicemaster_facilityservice_department'),
        ('laboratory', '0003_diagnosticorder_diagnosticresult_and_more'),
        ('patients', '0003_patient_person'),
        ('accounts', '0003_person_rolemaster_staffprofile_staffroleassignment_and_more'),
        ('surveillance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_code', models.CharField(max_length=50, unique=True)),
                ('disease_name', models.CharField(max_length=150)),
                ('transmission_type', models.CharField(max_length=50)),
                ('is_notifiable_state', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'disease_masters',
            },
        ),
        migrations.CreateModel(
            name='DiseaseSurveillanceCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=50, unique=True)),
                ('diagnosis_date', models.DateField(default=datetime.date.today)),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical')], default='MILD', max_length=20)),
                ('status', models.CharField(choices=[('SUSPECTED', 'Suspected'), ('PROBABLE', 'Probable'), ('CONFIRMED', 'Confirmed'), ('RECOVERED', 'Recovered'), ('DECEASED', 'Deceased')], default='SUSPECTED', max_length=20)),
                ('lab_confirmed', models.BooleanField(default=False)),
                ('investigation_notes', models.TextField(blank=True, default='')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnostic_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='surveillance_cases', to='laboratory.diagnosticresult')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='cases', to='surveillance.diseasemaster')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='surveillance_cases', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='surveillance_cases', to='patients.patient')),
                ('reporting_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reported_surveillance_cases', to='accounts.staffprofile')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='surveillance_cases', to='geography.ward')),
            ],
            options={
                'db_table': 'disease_surveillance_cases',
            },
        ),
        migrations.CreateModel(
            name='PublicHealthNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_authority', models.CharField(max_length=100)),
                ('transmission_status', models.CharField(choices=[('QUEUED', 'Queued'), ('DISPATCHED', 'Dispatched'), ('ACKNOWLEDGED', 'Acknowledged'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('dispatch_payload', models.JSONField()),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='surveillance.diseasesurveillancecase')),
            ],
            options={
                'db_table': 'public_health_notifications',
            },
        ),
    ]
