# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutreachActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(default='Household Survey / Slum Health Camp', max_length=100)),
                ('activity_date', models.DateField()),
                ('households_covered', models.IntegerField(default=50)),
                ('persons_screened', models.IntegerField(default=120)),
                ('vulnerable_identified', models.IntegerField(default=15)),
                ('conducted_by', models.CharField(default='ASHA & Staff Nurse Team', max_length=150)),
                ('summary_notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.ward')),
            ],
        ),
    ]
