# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Medicine Stock'), ('NEAR_EXPIRY', 'Near Expiry Medicine Batch'), ('EXPIRED', 'Expired Stock Alert'), ('REFERRAL_OVERDUE', 'Referral Overdue'), ('FOLLOWUP_OVERDUE', 'Follow-up Overdue'), ('LAB_PENDING', 'Lab Result Pending Verification'), ('DISEASE_THRESHOLD', 'Public Health Disease Anomaly Threshold Exceeded'), ('HIGH_RISK_FOLLOWUP', 'High-Risk Patient Follow-up Due'), ('MISSING_REPORT', 'Clinic Reporting Delayed')], max_length=40)),
                ('severity', models.CharField(choices=[('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('HIGH', 'High Severity'), ('CRITICAL', 'Critical Alert')], default='MEDIUM', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('NEW', 'New Alert'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
            ],
        ),
    ]
