# Generated by Django 6.1.1 on 2026-10-06 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.district'),
        ),
        migrations.AddField(
            model_name='alert',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Medicine Stock'), ('NEAR_EXPIRY', 'Near Expiry Medicine Batch'), ('EXPIRED', 'Expired Stock Alert'), ('REFERRAL_OVERDUE', 'Referral Overdue'), ('FOLLOWUP_OVERDUE', 'Follow-up Overdue'), ('LAB_PENDING', 'Lab Result Pending Verification'), ('DISEASE_THRESHOLD', 'Public Health Disease Anomaly Threshold Exceeded'), ('HIGH_RISK_FOLLOWUP', 'High-Risk Patient Follow-up Due'), ('MISSING_REPORT', 'Clinic Reporting Delayed'), ('INTELLIGENCE_TREND', 'Disease Trend Increase Signal'), ('INTELLIGENCE_LOCALITY', 'High Locality Concentration Signal'), ('INTELLIGENCE_FORECAST', 'Forecast Surveillance Signal'), ('INTELLIGENCE_SEASONALITY', 'Seasonal Surveillance Signal')], max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Informational Signal'), ('LOW', 'Low Severity'), ('MEDIUM', 'Medium Severity'), ('WARNING', 'Warning Signal'), ('HIGH', 'High Severity'), ('CRITICAL', 'Critical Alert')], default='MEDIUM', max_length=20),
        ),
    ]
