# Generated by Django 4.2.30 on 2026-09-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_servicemaster_facilityservice_department'),
        ('accounts', '0003_person_rolemaster_staffprofile_staffroleassignment_and_more'),
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('source_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source_entity_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='acknowledged_alerts', to='accounts.staffprofile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_alerts', to='facilities.facility')),
            ],
            options={
                'db_table': 'operational_alerts',
            },
        ),
    ]
