# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screening_date', models.DateField(auto_now_add=True)),
                ('hypertension_screened', models.BooleanField(default=True)),
                ('hypertension_diagnosed', models.BooleanField(default=False)),
                ('diabetes_screened', models.BooleanField(default=True)),
                ('diabetes_diagnosed', models.BooleanField(default=False)),
                ('risk_level', models.CharField(default='LOW', max_length=20)),
                ('treatment_status', models.CharField(default='UNDER_TREATMENT', max_length=30)),
                ('control_status', models.CharField(default='CONTROLLED', max_length=30)),
                ('last_bp', models.CharField(default='120/80', max_length=20)),
                ('last_glucose', models.IntegerField(default=110)),
                ('next_followup_due', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncd_records', to='patients.patient')),
            ],
        ),
    ]
