# Generated by Django 4.2.30 on 2026-09-23 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_person'),
        ('facilities', '0003_servicemaster_facilityservice_department'),
        ('visits', '0004_facilitydailycounter'),
        ('accounts', '0003_person_rolemaster_staffprofile_staffroleassignment_and_more'),
        ('ncd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCDCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_code', models.CharField(max_length=50)),
                ('diagnosis_date', models.DateField(default=datetime.date.today)),
                ('staging', models.CharField(blank=True, default='', max_length=50)),
                ('control_status', models.CharField(choices=[('SCREENED', 'Screened'), ('CONFIRMED', 'Confirmed'), ('CONTROLLED', 'Controlled'), ('UNCONTROLLED', 'Uncontrolled'), ('REMISSION', 'Remission')], default='SCREENED', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('treatment_plan', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ncd_conditions', to='patients.patient')),
                ('registering_doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registered_ncd_conditions', to='accounts.staffprofile')),
                ('registering_facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='registered_ncd_conditions', to='facilities.facility')),
            ],
            options={
                'db_table': 'ncd_conditions',
                'unique_together': {('patient', 'condition_code')},
            },
        ),
        migrations.CreateModel(
            name='NCDAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('blood_glucose_fasting', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('blood_glucose_postprandial', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hba1c', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('clinical_notes', models.TextField(blank=True, default='')),
                ('assessed_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='performed_ncd_assessments', to='accounts.staffprofile')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='assessments', to='ncd.ncdcondition')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ncd_assessments', to='visits.visit')),
            ],
            options={
                'db_table': 'ncd_assessments',
            },
        ),
    ]
