# Generated by Django 4.2.30 on 2026-09-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_servicemaster_facilityservice_department'),
        ('accounts', '0003_person_rolemaster_staffprofile_staffroleassignment_and_more'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor_user_id', models.BigIntegerField(blank=True, null=True)),
                ('actor_role_snapshot', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW_CONFIDENTIAL', 'View Confidential')], max_length=20)),
                ('table_name', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=100)),
                ('payload_before', models.JSONField(blank=True, null=True)),
                ('payload_after', models.JSONField(blank=True, null=True)),
                ('correlation_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('actor_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='audit_entries', to='accounts.staffprofile')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='audit_entries', to='facilities.facility')),
            ],
            options={
                'db_table': 'audit_log_entries',
            },
        ),
    ]
