# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(default='Yoga & Meditation', max_length=50)),
                ('instructor_name', models.CharField(default='Certified AYUSH Yoga Instructor', max_length=150)),
                ('session_date', models.DateField()),
                ('session_time', models.CharField(default='07:00 AM - 08:00 AM', max_length=30)),
                ('venue', models.CharField(default='Namma Clinic Wellness Area / Local Park', max_length=150)),
                ('participants_count', models.IntegerField(default=25)),
                ('incentive_amount_rs', models.DecimalField(decimal_places=2, default=250.0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
            ],
        ),
    ]
