BEGIN TRANSACTION;
CREATE TABLE "accounts_user" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "password" varchar(128) NOT NULL, "last_login" datetime NULL, "is_superuser" bool NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" bool NOT NULL, "is_active" bool NOT NULL, "date_joined" datetime NOT NULL, "full_name" varchar(150) NOT NULL, "role" varchar(30) NOT NULL, "phone" varchar(20) NOT NULL, "assigned_district_id" bigint NULL REFERENCES "geography_district" ("id") DEFERRABLE INITIALLY DEFERRED, "assigned_facility_id" bigint NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "accounts_user" VALUES(1,'pbkdf2_sha256$1500000$6XDKRoDEVYC8yiethQoe8b$4gi5kIlyvrKZsG7Zu5uhMiw2BnCDf2mkgUSYxAuGSB0=',NULL,1,'admin','','','admin@nammaclinic.gov.in',1,1,'2026-09-03 06:04:01.407202','System Administrator','SUPER_ADMIN','',NULL,NULL);
INSERT INTO "accounts_user" VALUES(2,'pbkdf2_sha256$1500000$ytb1gBFFGIkkXKMu3tWMnx$ZIFvEibxR5i1rGum4T3I47IP8nc7cmOXRElCPqZL/Fs=',NULL,0,'district','','','district@nammaclinic.gov.in',0,1,'2026-09-03 06:04:01.956294','Dr. Sunita Rao (District Health Officer)','DISTRICT_ADMIN','',1,NULL);
INSERT INTO "accounts_user" VALUES(3,'pbkdf2_sha256$1500000$MZb3axGMkH3mJoYx3JB1Wt$uyfRY7urPOVsDhzGSCC6FyFaixeCP5pcdvHofBgHFVI=',NULL,0,'hospital','','','hospital@nammaclinic.gov.in',0,1,'2026-09-03 06:04:02.489452','Dr. K. V. Sharma (Chief Medical Supt)','HOSPITAL_ADMIN','',NULL,2);
INSERT INTO "accounts_user" VALUES(4,'pbkdf2_sha256$1500000$6rEWzDYGUe9FXMhVMXPsb6$u6OgwKAakH2/nqVCKWEYfWMaSljPtegcq5Tc3HoOEEw=',NULL,0,'doctor','','','doctor@nammaclinic.gov.in',0,1,'2026-09-03 06:04:03.022956','Dr. Rajesh Kumar (Medical Officer)','MEDICAL_OFFICER','',NULL,7);
INSERT INTO "accounts_user" VALUES(5,'pbkdf2_sha256$1500000$Kzr3bpmvvq7bzbq1phsv7X$DOFbXfZrYm37Ff3USMPyQPOwQQSVM1bp/eTwlny9T+c=',NULL,0,'nurse','','','nurse@nammaclinic.gov.in',0,1,'2026-09-03 06:04:03.546928','Sister Priya Nair','STAFF_NURSE','',NULL,7);
INSERT INTO "accounts_user" VALUES(6,'pbkdf2_sha256$1500000$Ex33seiX8fk7GD7A36xTL3$3e5DrOJ25xB6FOOcwcMhVQf8+Kxb+CvzIUqUwi3djDc=',NULL,0,'lab','','','lab@nammaclinic.gov.in',0,1,'2026-09-03 06:04:04.070651','Mr. Suresh Gowda','LAB_TECHNICIAN','',NULL,7);
INSERT INTO "accounts_user" VALUES(7,'pbkdf2_sha256$1500000$tFaBWIRQQaTNxtsEIvZ8xM$it96afin2dMEWIyelWM79p2ckeH92gwkb2NsGGJT31A=',NULL,0,'pharmacy','','','pharmacy@nammaclinic.gov.in',0,1,'2026-09-03 06:04:04.605432','Mrs. Lakshmi Devi','PHARMACIST','',NULL,7);
INSERT INTO "accounts_user" VALUES(8,'pbkdf2_sha256$1500000$08NE6345v7FP8bfplJvrpL$Gp8XchVpelqdjXxVT5vnwHogHr5Gl3GbpW842JnSkWU=',NULL,0,'officer','','','officer@nammaclinic.gov.in',0,1,'2026-09-03 06:04:05.122211','Dr. Anil Mehta (Public Health Officer)','PUBLIC_HEALTH_OFFICER','',1,NULL);
CREATE TABLE "accounts_user_groups" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "accounts_user_user_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "alerts_alert" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "alert_type" varchar(40) NOT NULL, "severity" varchar(20) NOT NULL, "title" varchar(200) NOT NULL, "description" text NOT NULL, "status" varchar(20) NOT NULL, "created_at" datetime NOT NULL, "assigned_user_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "patient_id" bigint NULL REFERENCES "patients_patient" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "alerts_alert" VALUES(1,'LOW_STOCK','MEDIUM','Low Stock: Amlodipine 5mg Tablets','Current batch quantity is 35 units (reorder threshold is 80 units).','NEW','2026-09-03 06:04:05.688552',NULL,7,NULL);
INSERT INTO "alerts_alert" VALUES(2,'EXPIRED','HIGH','Expired Stock: Amoxicillin 500mg Batch','Batch BATCH-AMX-OLD expired on 15 days ago (40 units remaining).','NEW','2026-09-03 06:04:05.688552',NULL,7,NULL);
INSERT INTO "alerts_alert" VALUES(3,'DISEASE_THRESHOLD','CRITICAL','Public Health Alert: Fever Spike in Varthur Ward','15 cases of acute fever reported in last 7 days exceeding threshold.','NEW','2026-09-03 06:04:05.688552',NULL,7,NULL);
CREATE TABLE "ars_arsactionitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "task_description" text NOT NULL, "responsible_person" varchar(150) NOT NULL, "due_date" date NOT NULL, "status" varchar(20) NOT NULL, "meeting_id" bigint NOT NULL REFERENCES "ars_arsmeeting" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "ars_arsactionitem" VALUES(1,'Procure water purifier cartridge and lab reagent kits','Pharmacist Lakshmi','2026-09-08','IN_PROGRESS',1);
CREATE TABLE "ars_arsmeeting" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "meeting_date" date NOT NULL, "chairperson_name" varchar(150) NOT NULL, "attendees_count" integer NOT NULL, "agenda" text NOT NULL, "proceedings_summary" text NOT NULL, "untied_funds_spent_rs" decimal NOT NULL, "signed_by_chairman" bool NOT NULL, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "ars_arsmeeting" VALUES(1,'2026-08-24','Corporator Ward 12',8,'Untied Grant allocation for lab consumables & drinking water filter','Approved Rs. 8,500 for lab reagents and water purifier maintenance.',8500,1,7);
CREATE TABLE "ars_arsmember" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL, "designation" varchar(100) NOT NULL, "mobile" varchar(20) NOT NULL, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "ars_arsmember" VALUES(1,'Sri Ward Member','Chairman (Corporator)','',7);
INSERT INTO "ars_arsmember" VALUES(2,'Dr. Rajesh Kumar','Member Secretary (MO)','',7);
CREATE TABLE "audit_auditlog" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "username_snapshot" varchar(150) NOT NULL, "action" varchar(100) NOT NULL, "details" text NOT NULL, "ip_address" char(39) NULL, "timestamp" datetime NOT NULL, "facility_id" bigint NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "audit_auditlog" VALUES(1,'admin','SYSTEM_SEED_DEMO','Demo database seeded successfully.',NULL,'2026-09-03 06:04:05.688552',7,1);
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(150) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "group_id" integer NOT NULL REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED, "permission_id" integer NOT NULL REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "content_type_id" integer NOT NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "codename" varchar(100) NOT NULL, "name" varchar(255) NOT NULL);
INSERT INTO "auth_permission" VALUES(1,1,'add_logentry','Can add log entry');
INSERT INTO "auth_permission" VALUES(2,1,'change_logentry','Can change log entry');
INSERT INTO "auth_permission" VALUES(3,1,'delete_logentry','Can delete log entry');
INSERT INTO "auth_permission" VALUES(4,1,'view_logentry','Can view log entry');
INSERT INTO "auth_permission" VALUES(5,3,'add_permission','Can add permission');
INSERT INTO "auth_permission" VALUES(6,3,'change_permission','Can change permission');
INSERT INTO "auth_permission" VALUES(7,3,'delete_permission','Can delete permission');
INSERT INTO "auth_permission" VALUES(8,3,'view_permission','Can view permission');
INSERT INTO "auth_permission" VALUES(9,2,'add_group','Can add group');
INSERT INTO "auth_permission" VALUES(10,2,'change_group','Can change group');
INSERT INTO "auth_permission" VALUES(11,2,'delete_group','Can delete group');
INSERT INTO "auth_permission" VALUES(12,2,'view_group','Can view group');
INSERT INTO "auth_permission" VALUES(13,4,'add_contenttype','Can add content type');
INSERT INTO "auth_permission" VALUES(14,4,'change_contenttype','Can change content type');
INSERT INTO "auth_permission" VALUES(15,4,'delete_contenttype','Can delete content type');
INSERT INTO "auth_permission" VALUES(16,4,'view_contenttype','Can view content type');
INSERT INTO "auth_permission" VALUES(17,5,'add_session','Can add session');
INSERT INTO "auth_permission" VALUES(18,5,'change_session','Can change session');
INSERT INTO "auth_permission" VALUES(19,5,'delete_session','Can delete session');
INSERT INTO "auth_permission" VALUES(20,5,'view_session','Can view session');
INSERT INTO "auth_permission" VALUES(21,6,'add_user','Can add user');
INSERT INTO "auth_permission" VALUES(22,6,'change_user','Can change user');
INSERT INTO "auth_permission" VALUES(23,6,'delete_user','Can delete user');
INSERT INTO "auth_permission" VALUES(24,6,'view_user','Can view user');
INSERT INTO "auth_permission" VALUES(25,8,'add_state','Can add state');
INSERT INTO "auth_permission" VALUES(26,8,'change_state','Can change state');
INSERT INTO "auth_permission" VALUES(27,8,'delete_state','Can delete state');
INSERT INTO "auth_permission" VALUES(28,8,'view_state','Can view state');
INSERT INTO "auth_permission" VALUES(29,7,'add_district','Can add district');
INSERT INTO "auth_permission" VALUES(30,7,'change_district','Can change district');
INSERT INTO "auth_permission" VALUES(31,7,'delete_district','Can delete district');
INSERT INTO "auth_permission" VALUES(32,7,'view_district','Can view district');
INSERT INTO "auth_permission" VALUES(33,10,'add_zone','Can add zone');
INSERT INTO "auth_permission" VALUES(34,10,'change_zone','Can change zone');
INSERT INTO "auth_permission" VALUES(35,10,'delete_zone','Can delete zone');
INSERT INTO "auth_permission" VALUES(36,10,'view_zone','Can view zone');
INSERT INTO "auth_permission" VALUES(37,9,'add_ward','Can add ward');
INSERT INTO "auth_permission" VALUES(38,9,'change_ward','Can change ward');
INSERT INTO "auth_permission" VALUES(39,9,'delete_ward','Can delete ward');
INSERT INTO "auth_permission" VALUES(40,9,'view_ward','Can view ward');
INSERT INTO "auth_permission" VALUES(41,11,'add_facility','Can add facility');
INSERT INTO "auth_permission" VALUES(42,11,'change_facility','Can change facility');
INSERT INTO "auth_permission" VALUES(43,11,'delete_facility','Can delete facility');
INSERT INTO "auth_permission" VALUES(44,11,'view_facility','Can view facility');
INSERT INTO "auth_permission" VALUES(45,12,'add_facilityrelationship','Can add facility relationship');
INSERT INTO "auth_permission" VALUES(46,12,'change_facilityrelationship','Can change facility relationship');
INSERT INTO "auth_permission" VALUES(47,12,'delete_facilityrelationship','Can delete facility relationship');
INSERT INTO "auth_permission" VALUES(48,12,'view_facilityrelationship','Can view facility relationship');
INSERT INTO "auth_permission" VALUES(49,13,'add_household','Can add household');
INSERT INTO "auth_permission" VALUES(50,13,'change_household','Can change household');
INSERT INTO "auth_permission" VALUES(51,13,'delete_household','Can delete household');
INSERT INTO "auth_permission" VALUES(52,13,'view_household','Can view household');
INSERT INTO "auth_permission" VALUES(53,14,'add_patient','Can add patient');
INSERT INTO "auth_permission" VALUES(54,14,'change_patient','Can change patient');
INSERT INTO "auth_permission" VALUES(55,14,'delete_patient','Can delete patient');
INSERT INTO "auth_permission" VALUES(56,14,'view_patient','Can view patient');
INSERT INTO "auth_permission" VALUES(57,16,'add_visit','Can add visit');
INSERT INTO "auth_permission" VALUES(58,16,'change_visit','Can change visit');
INSERT INTO "auth_permission" VALUES(59,16,'delete_visit','Can delete visit');
INSERT INTO "auth_permission" VALUES(60,16,'view_visit','Can view visit');
INSERT INTO "auth_permission" VALUES(61,15,'add_token','Can add token');
INSERT INTO "auth_permission" VALUES(62,15,'change_token','Can change token');
INSERT INTO "auth_permission" VALUES(63,15,'delete_token','Can delete token');
INSERT INTO "auth_permission" VALUES(64,15,'view_token','Can view token');
INSERT INTO "auth_permission" VALUES(65,17,'add_triagevitals','Can add triage vitals');
INSERT INTO "auth_permission" VALUES(66,17,'change_triagevitals','Can change triage vitals');
INSERT INTO "auth_permission" VALUES(67,17,'delete_triagevitals','Can delete triage vitals');
INSERT INTO "auth_permission" VALUES(68,17,'view_triagevitals','Can view triage vitals');
INSERT INTO "auth_permission" VALUES(69,18,'add_consultation','Can add consultation');
INSERT INTO "auth_permission" VALUES(70,18,'change_consultation','Can change consultation');
INSERT INTO "auth_permission" VALUES(71,18,'delete_consultation','Can delete consultation');
INSERT INTO "auth_permission" VALUES(72,18,'view_consultation','Can view consultation');
INSERT INTO "auth_permission" VALUES(73,19,'add_prescription','Can add prescription');
INSERT INTO "auth_permission" VALUES(74,19,'change_prescription','Can change prescription');
INSERT INTO "auth_permission" VALUES(75,19,'delete_prescription','Can delete prescription');
INSERT INTO "auth_permission" VALUES(76,19,'view_prescription','Can view prescription');
INSERT INTO "auth_permission" VALUES(77,20,'add_prescriptionitem','Can add prescription item');
INSERT INTO "auth_permission" VALUES(78,20,'change_prescriptionitem','Can change prescription item');
INSERT INTO "auth_permission" VALUES(79,20,'delete_prescriptionitem','Can delete prescription item');
INSERT INTO "auth_permission" VALUES(80,20,'view_prescriptionitem','Can view prescription item');
INSERT INTO "auth_permission" VALUES(81,24,'add_labtestmaster','Can add lab test master');
INSERT INTO "auth_permission" VALUES(82,24,'change_labtestmaster','Can change lab test master');
INSERT INTO "auth_permission" VALUES(83,24,'delete_labtestmaster','Can delete lab test master');
INSERT INTO "auth_permission" VALUES(84,24,'view_labtestmaster','Can view lab test master');
INSERT INTO "auth_permission" VALUES(85,21,'add_laborder','Can add lab order');
INSERT INTO "auth_permission" VALUES(86,21,'change_laborder','Can change lab order');
INSERT INTO "auth_permission" VALUES(87,21,'delete_laborder','Can delete lab order');
INSERT INTO "auth_permission" VALUES(88,21,'view_laborder','Can view lab order');
INSERT INTO "auth_permission" VALUES(89,22,'add_labresult','Can add lab result');
INSERT INTO "auth_permission" VALUES(90,22,'change_labresult','Can change lab result');
INSERT INTO "auth_permission" VALUES(91,22,'delete_labresult','Can delete lab result');
INSERT INTO "auth_permission" VALUES(92,22,'view_labresult','Can view lab result');
INSERT INTO "auth_permission" VALUES(93,23,'add_labsample','Can add lab sample');
INSERT INTO "auth_permission" VALUES(94,23,'change_labsample','Can change lab sample');
INSERT INTO "auth_permission" VALUES(95,23,'delete_labsample','Can delete lab sample');
INSERT INTO "auth_permission" VALUES(96,23,'view_labsample','Can view lab sample');
INSERT INTO "auth_permission" VALUES(97,27,'add_medicinemaster','Can add medicine master');
INSERT INTO "auth_permission" VALUES(98,27,'change_medicinemaster','Can change medicine master');
INSERT INTO "auth_permission" VALUES(99,27,'delete_medicinemaster','Can delete medicine master');
INSERT INTO "auth_permission" VALUES(100,27,'view_medicinemaster','Can view medicine master');
INSERT INTO "auth_permission" VALUES(101,26,'add_medicinebatch','Can add medicine batch');
INSERT INTO "auth_permission" VALUES(102,26,'change_medicinebatch','Can change medicine batch');
INSERT INTO "auth_permission" VALUES(103,26,'delete_medicinebatch','Can delete medicine batch');
INSERT INTO "auth_permission" VALUES(104,26,'view_medicinebatch','Can view medicine batch');
INSERT INTO "auth_permission" VALUES(105,25,'add_inventorytransaction','Can add inventory transaction');
INSERT INTO "auth_permission" VALUES(106,25,'change_inventorytransaction','Can change inventory transaction');
INSERT INTO "auth_permission" VALUES(107,25,'delete_inventorytransaction','Can delete inventory transaction');
INSERT INTO "auth_permission" VALUES(108,25,'view_inventorytransaction','Can view inventory transaction');
INSERT INTO "auth_permission" VALUES(109,29,'add_referral','Can add referral');
INSERT INTO "auth_permission" VALUES(110,29,'change_referral','Can change referral');
INSERT INTO "auth_permission" VALUES(111,29,'delete_referral','Can delete referral');
INSERT INTO "auth_permission" VALUES(112,29,'view_referral','Can view referral');
INSERT INTO "auth_permission" VALUES(113,28,'add_followup','Can add follow up');
INSERT INTO "auth_permission" VALUES(114,28,'change_followup','Can change follow up');
INSERT INTO "auth_permission" VALUES(115,28,'delete_followup','Can delete follow up');
INSERT INTO "auth_permission" VALUES(116,28,'view_followup','Can view follow up');
INSERT INTO "auth_permission" VALUES(117,30,'add_referralresponse','Can add referral response');
INSERT INTO "auth_permission" VALUES(118,30,'change_referralresponse','Can change referral response');
INSERT INTO "auth_permission" VALUES(119,30,'delete_referralresponse','Can delete referral response');
INSERT INTO "auth_permission" VALUES(120,30,'view_referralresponse','Can view referral response');
INSERT INTO "auth_permission" VALUES(121,31,'add_ncdrecord','Can add ncd record');
INSERT INTO "auth_permission" VALUES(122,31,'change_ncdrecord','Can change ncd record');
INSERT INTO "auth_permission" VALUES(123,31,'delete_ncdrecord','Can delete ncd record');
INSERT INTO "auth_permission" VALUES(124,31,'view_ncdrecord','Can view ncd record');
INSERT INTO "auth_permission" VALUES(125,32,'add_diseasecase','Can add disease case');
INSERT INTO "auth_permission" VALUES(126,32,'change_diseasecase','Can change disease case');
INSERT INTO "auth_permission" VALUES(127,32,'delete_diseasecase','Can delete disease case');
INSERT INTO "auth_permission" VALUES(128,32,'view_diseasecase','Can view disease case');
INSERT INTO "auth_permission" VALUES(129,33,'add_teleconsultation','Can add teleconsultation');
INSERT INTO "auth_permission" VALUES(130,33,'change_teleconsultation','Can change teleconsultation');
INSERT INTO "auth_permission" VALUES(131,33,'delete_teleconsultation','Can delete teleconsultation');
INSERT INTO "auth_permission" VALUES(132,33,'view_teleconsultation','Can view teleconsultation');
INSERT INTO "auth_permission" VALUES(133,34,'add_outreachactivity','Can add outreach activity');
INSERT INTO "auth_permission" VALUES(134,34,'change_outreachactivity','Can change outreach activity');
INSERT INTO "auth_permission" VALUES(135,34,'delete_outreachactivity','Can delete outreach activity');
INSERT INTO "auth_permission" VALUES(136,34,'view_outreachactivity','Can view outreach activity');
INSERT INTO "auth_permission" VALUES(137,35,'add_wellnesssession','Can add wellness session');
INSERT INTO "auth_permission" VALUES(138,35,'change_wellnesssession','Can change wellness session');
INSERT INTO "auth_permission" VALUES(139,35,'delete_wellnesssession','Can delete wellness session');
INSERT INTO "auth_permission" VALUES(140,35,'view_wellnesssession','Can view wellness session');
INSERT INTO "auth_permission" VALUES(141,37,'add_arsmeeting','Can add ars meeting');
INSERT INTO "auth_permission" VALUES(142,37,'change_arsmeeting','Can change ars meeting');
INSERT INTO "auth_permission" VALUES(143,37,'delete_arsmeeting','Can delete ars meeting');
INSERT INTO "auth_permission" VALUES(144,37,'view_arsmeeting','Can view ars meeting');
INSERT INTO "auth_permission" VALUES(145,36,'add_arsactionitem','Can add ars action item');
INSERT INTO "auth_permission" VALUES(146,36,'change_arsactionitem','Can change ars action item');
INSERT INTO "auth_permission" VALUES(147,36,'delete_arsactionitem','Can delete ars action item');
INSERT INTO "auth_permission" VALUES(148,36,'view_arsactionitem','Can view ars action item');
INSERT INTO "auth_permission" VALUES(149,38,'add_arsmember','Can add ars member');
INSERT INTO "auth_permission" VALUES(150,38,'change_arsmember','Can change ars member');
INSERT INTO "auth_permission" VALUES(151,38,'delete_arsmember','Can delete ars member');
INSERT INTO "auth_permission" VALUES(152,38,'view_arsmember','Can view ars member');
INSERT INTO "auth_permission" VALUES(153,39,'add_biomedicalwastelog','Can add biomedical waste log');
INSERT INTO "auth_permission" VALUES(154,39,'change_biomedicalwastelog','Can change biomedical waste log');
INSERT INTO "auth_permission" VALUES(155,39,'delete_biomedicalwastelog','Can delete biomedical waste log');
INSERT INTO "auth_permission" VALUES(156,39,'view_biomedicalwastelog','Can view biomedical waste log');
INSERT INTO "auth_permission" VALUES(157,40,'add_qualitychecklist','Can add quality checklist');
INSERT INTO "auth_permission" VALUES(158,40,'change_qualitychecklist','Can change quality checklist');
INSERT INTO "auth_permission" VALUES(159,40,'delete_qualitychecklist','Can delete quality checklist');
INSERT INTO "auth_permission" VALUES(160,40,'view_qualitychecklist','Can view quality checklist');
INSERT INTO "auth_permission" VALUES(161,41,'add_reportexportlog','Can add report export log');
INSERT INTO "auth_permission" VALUES(162,41,'change_reportexportlog','Can change report export log');
INSERT INTO "auth_permission" VALUES(163,41,'delete_reportexportlog','Can delete report export log');
INSERT INTO "auth_permission" VALUES(164,41,'view_reportexportlog','Can view report export log');
INSERT INTO "auth_permission" VALUES(165,42,'add_alert','Can add alert');
INSERT INTO "auth_permission" VALUES(166,42,'change_alert','Can change alert');
INSERT INTO "auth_permission" VALUES(167,42,'delete_alert','Can delete alert');
INSERT INTO "auth_permission" VALUES(168,42,'view_alert','Can view alert');
INSERT INTO "auth_permission" VALUES(169,43,'add_integrationconfiguration','Can add integration configuration');
INSERT INTO "auth_permission" VALUES(170,43,'change_integrationconfiguration','Can change integration configuration');
INSERT INTO "auth_permission" VALUES(171,43,'delete_integrationconfiguration','Can delete integration configuration');
INSERT INTO "auth_permission" VALUES(172,43,'view_integrationconfiguration','Can view integration configuration');
INSERT INTO "auth_permission" VALUES(173,44,'add_complianceitem','Can add compliance item');
INSERT INTO "auth_permission" VALUES(174,44,'change_complianceitem','Can change compliance item');
INSERT INTO "auth_permission" VALUES(175,44,'delete_complianceitem','Can delete compliance item');
INSERT INTO "auth_permission" VALUES(176,44,'view_complianceitem','Can view compliance item');
INSERT INTO "auth_permission" VALUES(177,45,'add_auditlog','Can add audit log');
INSERT INTO "auth_permission" VALUES(178,45,'change_auditlog','Can change audit log');
INSERT INTO "auth_permission" VALUES(179,45,'delete_auditlog','Can delete audit log');
INSERT INTO "auth_permission" VALUES(180,45,'view_auditlog','Can view audit log');
CREATE TABLE "compliance_complianceitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "requirement_id" varchar(50) NOT NULL UNIQUE, "requirement_text" text NOT NULL, "source_document" varchar(100) NOT NULL, "classification" varchar(50) NOT NULL, "application_module" varchar(100) NOT NULL, "status" varchar(30) NOT NULL, "explanation" text NOT NULL);
INSERT INTO "compliance_complianceitem" VALUES(1,'REQ-OFF-001','Provide comprehensive primary health care in urban areas','ULB ROK Booklet','OFFICIAL BOOKLET REQUIREMENT','Clinical / Consultation','FULLY_COVERED','Complete 12 service package delivery supported.');
INSERT INTO "compliance_complianceitem" VALUES(2,'REQ-KM-003','First-Expiry First-Out (FEFO) batch management and stock alerts','K Mati Proposal','K MATI PROPOSAL','Pharmacy / Inventory','FULLY_COVERED','Automated batch expiry sorting and low stock alerts implemented.');
CREATE TABLE "consultations_consultation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "chief_complaint" text NOT NULL, "clinical_history" text NOT NULL, "clinical_assessment" text NOT NULL, "diagnosis_code" varchar(50) NOT NULL, "diagnosis_name" varchar(200) NOT NULL, "treatment_plan" text NOT NULL, "follow_up_date" date NULL, "clinical_notes" text NOT NULL, "created_at" datetime NOT NULL, "doctor_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "patient_id" bigint NOT NULL REFERENCES "patients_patient" ("id") DEFERRABLE INITIALLY DEFERRED, "visit_id" bigint NOT NULL UNIQUE REFERENCES "visits_visit" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "consultations_consultation" VALUES(1,'Dizziness and fatigue for 5 days','Known history of hypertension for 2 years, irregular medication adherence.','Elevated BP 148/96 and Random Glucose 185 mg/dL. Suspected uncontrolled Type 2 Diabetes.','E11.9 / I10','Type 2 Diabetes Mellitus with Essential Hypertension','Initiate Metformin 500mg BD, Amlodipine 5mg OD. Refer to Main Hospital B Cardiology Hub.','2026-09-17','Advised low sodium diet, exercise, and strict medication adherence.','2026-09-03 06:04:05.671666',4,7,1,1);
CREATE TABLE "consultations_prescription" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" date NOT NULL, "status" varchar(20) NOT NULL, "notes" text NOT NULL, "consultation_id" bigint NOT NULL UNIQUE REFERENCES "consultations_consultation" ("id") DEFERRABLE INITIALLY DEFERRED, "doctor_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "patient_id" bigint NOT NULL REFERENCES "patients_patient" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "consultations_prescription" VALUES(1,'2026-09-03','DISPENSED','',1,4,7,1);
CREATE TABLE "consultations_prescriptionitem" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "medicine_name" varchar(150) NOT NULL, "dosage" varchar(50) NOT NULL, "frequency" varchar(50) NOT NULL, "duration_days" integer NOT NULL, "quantity" integer NOT NULL, "status" varchar(20) NOT NULL, "prescription_id" bigint NOT NULL REFERENCES "consultations_prescription" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "consultations_prescriptionitem" VALUES(1,'Metformin 500 mg Tablet','1-0-1 After Food','Twice Daily',14,28,'DISPENSED',1);
INSERT INTO "consultations_prescriptionitem" VALUES(2,'Amlodipine 5 mg Tablet','1-0-0 Morning','Once Daily',14,14,'DISPENSED',1);
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint unsigned NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED, "user_id" bigint NOT NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "action_time" datetime NOT NULL);
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
INSERT INTO "django_content_type" VALUES(1,'admin','logentry');
INSERT INTO "django_content_type" VALUES(2,'auth','group');
INSERT INTO "django_content_type" VALUES(3,'auth','permission');
INSERT INTO "django_content_type" VALUES(4,'contenttypes','contenttype');
INSERT INTO "django_content_type" VALUES(5,'sessions','session');
INSERT INTO "django_content_type" VALUES(6,'accounts','user');
INSERT INTO "django_content_type" VALUES(7,'geography','district');
INSERT INTO "django_content_type" VALUES(8,'geography','state');
INSERT INTO "django_content_type" VALUES(9,'geography','ward');
INSERT INTO "django_content_type" VALUES(10,'geography','zone');
INSERT INTO "django_content_type" VALUES(11,'facilities','facility');
INSERT INTO "django_content_type" VALUES(12,'facilities','facilityrelationship');
INSERT INTO "django_content_type" VALUES(13,'patients','household');
INSERT INTO "django_content_type" VALUES(14,'patients','patient');
INSERT INTO "django_content_type" VALUES(15,'visits','token');
INSERT INTO "django_content_type" VALUES(16,'visits','visit');
INSERT INTO "django_content_type" VALUES(17,'triage','triagevitals');
INSERT INTO "django_content_type" VALUES(18,'consultations','consultation');
INSERT INTO "django_content_type" VALUES(19,'consultations','prescription');
INSERT INTO "django_content_type" VALUES(20,'consultations','prescriptionitem');
INSERT INTO "django_content_type" VALUES(21,'laboratory','laborder');
INSERT INTO "django_content_type" VALUES(22,'laboratory','labresult');
INSERT INTO "django_content_type" VALUES(23,'laboratory','labsample');
INSERT INTO "django_content_type" VALUES(24,'laboratory','labtestmaster');
INSERT INTO "django_content_type" VALUES(25,'pharmacy','inventorytransaction');
INSERT INTO "django_content_type" VALUES(26,'pharmacy','medicinebatch');
INSERT INTO "django_content_type" VALUES(27,'pharmacy','medicinemaster');
INSERT INTO "django_content_type" VALUES(28,'referrals','followup');
INSERT INTO "django_content_type" VALUES(29,'referrals','referral');
INSERT INTO "django_content_type" VALUES(30,'referrals','referralresponse');
INSERT INTO "django_content_type" VALUES(31,'ncd','ncdrecord');
INSERT INTO "django_content_type" VALUES(32,'surveillance','diseasecase');
INSERT INTO "django_content_type" VALUES(33,'telemedicine','teleconsultation');
INSERT INTO "django_content_type" VALUES(34,'outreach','outreachactivity');
INSERT INTO "django_content_type" VALUES(35,'wellness','wellnesssession');
INSERT INTO "django_content_type" VALUES(36,'ars','arsactionitem');
INSERT INTO "django_content_type" VALUES(37,'ars','arsmeeting');
INSERT INTO "django_content_type" VALUES(38,'ars','arsmember');
INSERT INTO "django_content_type" VALUES(39,'quality','biomedicalwastelog');
INSERT INTO "django_content_type" VALUES(40,'quality','qualitychecklist');
INSERT INTO "django_content_type" VALUES(41,'reports','reportexportlog');
INSERT INTO "django_content_type" VALUES(42,'alerts','alert');
INSERT INTO "django_content_type" VALUES(43,'integrations','integrationconfiguration');
INSERT INTO "django_content_type" VALUES(44,'compliance','complianceitem');
INSERT INTO "django_content_type" VALUES(45,'audit','auditlog');
CREATE TABLE "django_migrations" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "app" varchar(255) NOT NULL, "name" varchar(255) NOT NULL, "applied" datetime NOT NULL);
INSERT INTO "django_migrations" VALUES(1,'geography','0001_initial','2026-09-03 06:03:42.901669');
INSERT INTO "django_migrations" VALUES(2,'facilities','0001_initial','2026-09-03 06:03:42.918992');
INSERT INTO "django_migrations" VALUES(3,'contenttypes','0001_initial','2026-09-03 06:03:42.927894');
INSERT INTO "django_migrations" VALUES(4,'contenttypes','0002_remove_content_type_name','2026-09-03 06:03:42.942202');
INSERT INTO "django_migrations" VALUES(5,'auth','0001_initial','2026-09-03 06:03:42.957839');
INSERT INTO "django_migrations" VALUES(6,'auth','0002_alter_permission_name_max_length','2026-09-03 06:03:42.968889');
INSERT INTO "django_migrations" VALUES(7,'auth','0003_alter_user_email_max_length','2026-09-03 06:03:42.975734');
INSERT INTO "django_migrations" VALUES(8,'auth','0004_alter_user_username_opts','2026-09-03 06:03:42.983146');
INSERT INTO "django_migrations" VALUES(9,'auth','0005_alter_user_last_login_null','2026-09-03 06:03:42.990246');
INSERT INTO "django_migrations" VALUES(10,'auth','0006_require_contenttypes_0002','2026-09-03 06:03:42.994936');
INSERT INTO "django_migrations" VALUES(11,'auth','0007_alter_validators_add_error_messages','2026-09-03 06:03:43.003540');
INSERT INTO "django_migrations" VALUES(12,'auth','0008_alter_user_username_max_length','2026-09-03 06:03:43.010968');
INSERT INTO "django_migrations" VALUES(13,'auth','0009_alter_user_last_name_max_length','2026-09-03 06:03:43.018356');
INSERT INTO "django_migrations" VALUES(14,'auth','0010_alter_group_name_max_length','2026-09-03 06:03:43.027809');
INSERT INTO "django_migrations" VALUES(15,'auth','0011_update_proxy_permissions','2026-09-03 06:03:43.038937');
INSERT INTO "django_migrations" VALUES(16,'auth','0012_alter_user_first_name_max_length','2026-09-03 06:03:43.046188');
INSERT INTO "django_migrations" VALUES(17,'accounts','0001_initial','2026-09-03 06:03:43.062627');
INSERT INTO "django_migrations" VALUES(18,'admin','0001_initial','2026-09-03 06:03:43.079388');
INSERT INTO "django_migrations" VALUES(19,'admin','0002_logentry_remove_auto_add','2026-09-03 06:03:43.090210');
INSERT INTO "django_migrations" VALUES(20,'admin','0003_logentry_add_action_flag_choices','2026-09-03 06:03:43.099832');
INSERT INTO "django_migrations" VALUES(21,'patients','0001_initial','2026-09-03 06:03:43.124330');
INSERT INTO "django_migrations" VALUES(22,'alerts','0001_initial','2026-09-03 06:03:43.143722');
INSERT INTO "django_migrations" VALUES(23,'ars','0001_initial','2026-09-03 06:03:43.179361');
INSERT INTO "django_migrations" VALUES(24,'audit','0001_initial','2026-09-03 06:03:43.204880');
INSERT INTO "django_migrations" VALUES(25,'compliance','0001_initial','2026-09-03 06:03:43.222301');
INSERT INTO "django_migrations" VALUES(26,'visits','0001_initial','2026-09-03 06:03:43.278193');
INSERT INTO "django_migrations" VALUES(27,'consultations','0001_initial','2026-09-03 06:03:43.338956');
INSERT INTO "django_migrations" VALUES(28,'integrations','0001_initial','2026-09-03 06:03:43.344912');
INSERT INTO "django_migrations" VALUES(29,'laboratory','0001_initial','2026-09-03 06:03:43.395858');
INSERT INTO "django_migrations" VALUES(30,'ncd','0001_initial','2026-09-03 06:03:43.419473');
INSERT INTO "django_migrations" VALUES(31,'outreach','0001_initial','2026-09-03 06:03:43.454569');
INSERT INTO "django_migrations" VALUES(32,'pharmacy','0001_initial','2026-09-03 06:03:43.495444');
INSERT INTO "django_migrations" VALUES(33,'quality','0001_initial','2026-09-03 06:03:43.545930');
INSERT INTO "django_migrations" VALUES(34,'referrals','0001_initial','2026-09-03 06:03:43.619246');
INSERT INTO "django_migrations" VALUES(35,'sessions','0001_initial','2026-09-03 06:03:43.631347');
INSERT INTO "django_migrations" VALUES(36,'surveillance','0001_initial','2026-09-03 06:03:43.650871');
INSERT INTO "django_migrations" VALUES(37,'telemedicine','0001_initial','2026-09-03 06:03:43.731144');
INSERT INTO "django_migrations" VALUES(38,'triage','0001_initial','2026-09-03 06:03:43.762464');
INSERT INTO "django_migrations" VALUES(39,'wellness','0001_initial','2026-09-03 06:03:43.787674');
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" datetime NOT NULL);
CREATE TABLE "facilities_facility" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "facility_code" varchar(50) NOT NULL UNIQUE, "facility_name" varchar(200) NOT NULL, "facility_type" varchar(30) NOT NULL, "city_or_ulb" varchar(100) NOT NULL, "urban_rural" varchar(10) NOT NULL, "address" text NOT NULL, "latitude" decimal NOT NULL, "longitude" decimal NOT NULL, "population_served" integer NOT NULL, "vulnerable_population" integer NOT NULL, "phone" varchar(20) NOT NULL, "email" varchar(254) NOT NULL, "opening_time" varchar(20) NOT NULL, "closing_time" varchar(20) NOT NULL, "emergency_available" bool NOT NULL, "lab_available" bool NOT NULL, "pharmacy_available" bool NOT NULL, "teleconsultation_available" bool NOT NULL, "bed_capacity" integer NOT NULL, "services" text NOT NULL, "specialists" text NOT NULL, "status" varchar(20) NOT NULL, "created_at" datetime NOT NULL, "updated_at" datetime NOT NULL, "district_id" bigint NOT NULL REFERENCES "geography_district" ("id") DEFERRABLE INITIALLY DEFERRED, "parent_facility_id" bigint NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "state_id" bigint NOT NULL REFERENCES "geography_state" ("id") DEFERRABLE INITIALLY DEFERRED, "ward_id" bigint NULL REFERENCES "geography_ward" ("id") DEFERRABLE INITIALLY DEFERRED, "zone_id" bigint NULL REFERENCES "geography_zone" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "facilities_facility" VALUES(1,'HOSP-A-01','Victoria Hospital & Medical Center','MAIN_HOSPITAL','BBMP Central','URBAN','',12.9634,77.575,500000,5000,'','','09:00 AM','04:30 PM',1,1,1,1,750,'Cardiology, Nephrology, General Surgery, Emergency, ICU, Teleconsultation Hub','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',1,NULL,1,1,1);
INSERT INTO "facilities_facility" VALUES(2,'HOSP-B-01','KC General Secondary Hospital','MAIN_HOSPITAL','BBMP South','URBAN','',12.9915,77.5712,350000,5000,'','','09:00 AM','04:30 PM',1,1,1,1,350,'General Medicine, Cardiology Specialist, Pediatrics, Obstetrics, Diagnostics','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',1,NULL,1,3,2);
INSERT INTO "facilities_facility" VALUES(3,'DIAG-D-01','BBMP Central Diagnostic Center','DIAGNOSTIC_CENTER','BBMP Central','URBAN','',12.978,77.584,200000,5000,'','','09:00 AM','04:30 PM',0,1,1,1,0,'Advanced Biochemistry, Pathology, X-Ray, Ultrasound, CT Scan','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',1,NULL,1,1,1);
INSERT INTO "facilities_facility" VALUES(4,'NC-A1-01','Indiranagar Namma Clinic (UHWC)','NAMMA_CLINIC','BBMP East','URBAN','',12.9719,77.6412,18500,6500,'','','09:00 AM','04:30 PM',0,1,1,1,0,'General OPD, NCD Screening, ANC/PNC Care, Immunization, Basic Diagnostics, Pharmacy','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',1,1,1,1,1);
INSERT INTO "facilities_facility" VALUES(5,'NC-A2-02','Ulsoor Namma Clinic (UHWC)','NAMMA_CLINIC','BBMP East','URBAN','',12.9816,77.62,17000,5200,'','','09:00 AM','04:30 PM',0,1,1,1,0,'General OPD, NCD Screening, ANC/PNC Care, Immunization, Basic Diagnostics, Pharmacy','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',1,1,1,2,1);
INSERT INTO "facilities_facility" VALUES(6,'UC-A3-03','Domlur Urban Primary Clinic','URBAN_CLINIC','BBMP East','URBAN','',12.96,77.638,21000,5000,'','','09:00 AM','04:30 PM',0,1,1,1,0,'General OPD, NCD Screening, ANC/PNC Care, Immunization, Basic Diagnostics, Pharmacy','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',1,1,1,1,1);
INSERT INTO "facilities_facility" VALUES(7,'RC-A4-04','Varthur Rural Primary Clinic A4','RURAL_CLINIC','BBMP East Peripheral','RURAL','',12.9406,77.747,19000,7200,'','','09:00 AM','04:30 PM',0,1,1,1,0,'General OPD, NCD Screening, ANC/PNC Care, Immunization, Basic Diagnostics, Pharmacy','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',1,1,1,5,1);
INSERT INTO "facilities_facility" VALUES(8,'VC-A4-1','Gunjur Village Satellite Clinic','VILLAGE_CLINIC','BBMP','RURAL','',12.93,77.755,8000,5000,'','','09:00 AM','04:30 PM',0,1,1,1,0,'General OPD, NCD Screening, ANC/PNC Care, Immunization, Basic Diagnostics, Pharmacy','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',1,7,1,5,1);
INSERT INTO "facilities_facility" VALUES(9,'VC-A4-2','Balagere Village Health Post','VILLAGE_CLINIC','BBMP','RURAL','',12.938,77.761,6500,5000,'','','09:00 AM','04:30 PM',0,1,1,1,0,'General OPD, NCD Screening, ANC/PNC Care, Immunization, Basic Diagnostics, Pharmacy','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',1,7,1,5,1);
INSERT INTO "facilities_facility" VALUES(10,'NC-B1-01','Jayanagar Namma Clinic (UHWC)','NAMMA_CLINIC','BBMP South','URBAN','',12.925,77.5938,20000,4800,'','','09:00 AM','04:30 PM',0,1,1,1,0,'General OPD, NCD Screening, ANC/PNC Care, Immunization, Basic Diagnostics, Pharmacy','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',1,2,1,3,2);
INSERT INTO "facilities_facility" VALUES(11,'RC-B2-02','Bannerghatta Rural Clinic','RURAL_CLINIC','BBMP','RURAL','',12.8,77.58,16000,5000,'','','09:00 AM','04:30 PM',0,1,1,1,0,'General OPD, NCD Screening, ANC/PNC Care, Immunization, Basic Diagnostics, Pharmacy','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',1,2,1,4,2);
INSERT INTO "facilities_facility" VALUES(12,'HOSP-C-01','Hoskote District General Hospital','MAIN_HOSPITAL','Hoskote Town','RURAL','',13.07,77.79,250000,5000,'','','09:00 AM','04:30 PM',1,1,1,1,200,'General OPD, NCD Screening, ANC/PNC Care, Immunization, Basic Diagnostics, Pharmacy','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',2,NULL,1,NULL,3);
INSERT INTO "facilities_facility" VALUES(13,'NC-C1-01','Hoskote Town Namma Clinic','NAMMA_CLINIC','Hoskote Town','URBAN','',13.072,77.795,18000,5000,'','','09:00 AM','04:30 PM',0,1,1,1,0,'General OPD, NCD Screening, ANC/PNC Care, Immunization, Basic Diagnostics, Pharmacy','General Physician, Staff Nurse, Lab Tech, Pharmacist','ACTIVE','2026-09-03 06:04:01.407202','2026-09-03 06:04:01.407202',2,12,1,NULL,3);
CREATE TABLE "facilities_facilityrelationship" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "relationship_type" varchar(30) NOT NULL, "service" varchar(100) NOT NULL, "priority" varchar(20) NOT NULL, "distance_km" decimal NOT NULL, "active" bool NOT NULL, "notes" text NOT NULL, "created_at" datetime NOT NULL, "destination_facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "source_facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "facilities_facilityrelationship" VALUES(1,'REFERRAL','Routine Primary Care','PRIMARY',4.2,1,'','2026-09-03 06:04:01.407202',4,7);
INSERT INTO "facilities_facilityrelationship" VALUES(2,'SPECIALIST','Cardiology & Internal Medicine','SECONDARY',8.5,1,'','2026-09-03 06:04:01.407202',2,7);
INSERT INTO "facilities_facilityrelationship" VALUES(3,'EMERGENCY','Trauma & Intensive Care','EMERGENCY',12,1,'','2026-09-03 06:04:01.407202',1,7);
INSERT INTO "facilities_facilityrelationship" VALUES(4,'DIAGNOSTIC','Advanced Biochemistry & Ultrasound','PRIMARY',6,1,'','2026-09-03 06:04:01.407202',3,7);
INSERT INTO "facilities_facilityrelationship" VALUES(5,'TELECONSULTATION','Specialist Teleconsultation Hub','PRIMARY',5,1,'','2026-09-03 06:04:01.407202',1,7);
CREATE TABLE "geography_district" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "code" varchar(20) NOT NULL UNIQUE, "state_id" bigint NOT NULL REFERENCES "geography_state" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "geography_district" VALUES(1,'BBMP Central (Bengaluru Urban)','KA-BU',1);
INSERT INTO "geography_district" VALUES(2,'Bengaluru Rural','KA-BR',1);
CREATE TABLE "geography_state" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL UNIQUE, "code" varchar(10) NOT NULL UNIQUE);
INSERT INTO "geography_state" VALUES(1,'Karnataka','KA');
CREATE TABLE "geography_ward" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "ward_number" integer NOT NULL, "name" varchar(100) NOT NULL, "population" integer NOT NULL, "slum_population" integer NOT NULL, "zone_id" bigint NOT NULL REFERENCES "geography_zone" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "geography_ward" VALUES(1,12,'Indiranagar Ward',22000,6500,1);
INSERT INTO "geography_ward" VALUES(2,14,'Ulsoor Ward',19500,5200,1);
INSERT INTO "geography_ward" VALUES(3,45,'Jayanagar Ward',24000,4800,2);
INSERT INTO "geography_ward" VALUES(4,52,'JP Nagar Ward',21000,4100,2);
INSERT INTO "geography_ward" VALUES(5,1,'Varthur Rural Ward',18000,7200,3);
CREATE TABLE "geography_zone" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "name" varchar(100) NOT NULL, "code" varchar(20) NOT NULL, "district_id" bigint NOT NULL REFERENCES "geography_district" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "geography_zone" VALUES(1,'East Zone','Z-EAST',1);
INSERT INTO "geography_zone" VALUES(2,'South Zone','Z-SOUTH',1);
INSERT INTO "geography_zone" VALUES(3,'Hoskote Zone','Z-HOS',2);
CREATE TABLE "integrations_integrationconfiguration" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "system_name" varchar(50) NOT NULL UNIQUE, "display_name" varchar(150) NOT NULL, "status" varchar(20) NOT NULL, "last_sync_time" datetime NULL, "sync_status" varchar(30) NOT NULL, "notes" text NOT NULL);
INSERT INTO "integrations_integrationconfiguration" VALUES(1,'ABDM','Ayushman Bharat Digital Mission (ABDM)','MOCK',NULL,'SUCCESS','Local ABDM mock connector active.');
INSERT INTO "integrations_integrationconfiguration" VALUES(2,'ABHA','ABHA Health ID Gateway','MOCK',NULL,'SUCCESS','Local ABHA verification engine.');
INSERT INTO "integrations_integrationconfiguration" VALUES(3,'HMIS','Karnataka Health Management Information System','MOCK',NULL,'SUCCESS','Periodic HMIS export template ready.');
INSERT INTO "integrations_integrationconfiguration" VALUES(4,'E_AUSHADA','KSMSCL E-Aushada Drug Procurement Engine','MOCK',NULL,'SUCCESS','Direct indent sync mock interface.');
CREATE TABLE "laboratory_laborder" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "order_date" datetime NOT NULL, "status" varchar(30) NOT NULL, "consultation_id" bigint NULL REFERENCES "consultations_consultation" ("id") DEFERRABLE INITIALLY DEFERRED, "doctor_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "patient_id" bigint NOT NULL REFERENCES "patients_patient" ("id") DEFERRABLE INITIALLY DEFERRED, "test_master_id" bigint NOT NULL REFERENCES "laboratory_labtestmaster" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "laboratory_laborder" VALUES(1,'2026-09-03 06:04:05.686763','VERIFIED',1,4,7,1,1);
CREATE TABLE "laboratory_labresult" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "result_value" varchar(100) NOT NULL, "unit" varchar(20) NOT NULL, "reference_range" varchar(100) NOT NULL, "interpretation_flag" varchar(20) NOT NULL, "verified_at" datetime NOT NULL, "notes" text NOT NULL, "lab_order_id" bigint NOT NULL UNIQUE REFERENCES "laboratory_laborder" ("id") DEFERRABLE INITIALLY DEFERRED, "verified_by_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "laboratory_labresult" VALUES(1,'8.4','%','4.0 - 5.6 %','HIGH','2026-09-03 06:04:05.688552','Uncontrolled HbA1c level',1,6);
CREATE TABLE "laboratory_labsample" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "sample_type" varchar(50) NOT NULL, "sample_code" varchar(50) NOT NULL UNIQUE, "collected_at" datetime NOT NULL, "collected_by_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "lab_order_id" bigint NOT NULL UNIQUE REFERENCES "laboratory_laborder" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "laboratory_labsample" VALUES(1,'Blood','SMP-0001','2026-09-03 06:04:05.688552',6,1);
CREATE TABLE "laboratory_labtestmaster" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "code" varchar(50) NOT NULL UNIQUE, "name" varchar(150) NOT NULL, "category" varchar(50) NOT NULL, "reference_range" varchar(100) NOT NULL, "unit" varchar(20) NOT NULL);
INSERT INTO "laboratory_labtestmaster" VALUES(1,'L-HBA1C','HbA1c Glycated Hemoglobin','Diabetes','4.0 - 5.6 %','%');
INSERT INTO "laboratory_labtestmaster" VALUES(2,'L-FBG','Fasting Blood Glucose','Diabetes','70 - 100 mg/dL','mg/dL');
INSERT INTO "laboratory_labtestmaster" VALUES(3,'L-HB','Hemoglobin (Hb)','Hematology','12.0 - 15.5 g/dL','g/dL');
INSERT INTO "laboratory_labtestmaster" VALUES(4,'L-LIPID','Lipid Profile','Biochemistry','Desirable < 200 mg/dL','mg/dL');
INSERT INTO "laboratory_labtestmaster" VALUES(5,'L-DENGUE','Dengue NS1 Antigen Rapid Test','Serology','Negative','Result');
CREATE TABLE "ncd_ncdrecord" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "screening_date" date NOT NULL, "hypertension_screened" bool NOT NULL, "hypertension_diagnosed" bool NOT NULL, "diabetes_screened" bool NOT NULL, "diabetes_diagnosed" bool NOT NULL, "risk_level" varchar(20) NOT NULL, "treatment_status" varchar(30) NOT NULL, "control_status" varchar(30) NOT NULL, "last_bp" varchar(20) NOT NULL, "last_glucose" integer NOT NULL, "next_followup_due" date NULL, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "patient_id" bigint NOT NULL REFERENCES "patients_patient" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "ncd_ncdrecord" VALUES(1,'2026-09-03',1,1,1,1,'HIGH','UNDER_TREATMENT','UNCONTROLLED','148/96',185,'2026-09-17',7,1);
INSERT INTO "ncd_ncdrecord" VALUES(2,'2026-09-03',1,1,1,1,'MODERATE','UNDER_TREATMENT','CONTROLLED','130/84',125,'2026-10-03',5,3);
CREATE TABLE "outreach_outreachactivity" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "activity_type" varchar(100) NOT NULL, "activity_date" date NOT NULL, "households_covered" integer NOT NULL, "persons_screened" integer NOT NULL, "vulnerable_identified" integer NOT NULL, "conducted_by" varchar(150) NOT NULL, "summary_notes" text NOT NULL, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "ward_id" bigint NULL REFERENCES "geography_ward" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "outreach_outreachactivity" VALUES(1,'Slum Household NCD & Fever Survey','2026-08-31',65,140,18,'ASHA & Staff Nurse Team','',7,5);
CREATE TABLE "patients_household" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "household_id" varchar(50) NOT NULL UNIQUE, "head_name" varchar(150) NOT NULL, "address" text NOT NULL, "members_count" integer NOT NULL, "vulnerable_category" varchar(100) NOT NULL, "created_at" date NOT NULL, "ward_id" bigint NULL REFERENCES "geography_ward" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "patients_patient" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "patient_id" varchar(50) NOT NULL UNIQUE, "name" varchar(150) NOT NULL, "date_of_birth" date NULL, "age" integer NOT NULL, "gender" varchar(10) NOT NULL, "mobile" varchar(20) NOT NULL, "address" text NOT NULL, "ABHA_ID_DEMO" varchar(50) NOT NULL, "emergency_contact" varchar(100) NOT NULL, "vulnerability_information" varchar(100) NOT NULL, "registration_date" date NOT NULL, "district_id" bigint NULL REFERENCES "geography_district" ("id") DEFERRABLE INITIALLY DEFERRED, "registered_at_facility_id" bigint NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "ward_id" bigint NULL REFERENCES "geography_ward" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "patients_patient" VALUES(1,'NC-20260901-001','Ramesh Kumar','1974-05-12',52,'MALE','9876543210','House #45, Near Govt School, Varthur Slum Area','91-8765-4321-0987','9876543211 (Wife - Sunita)','Slum Household BPL','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(2,'NC-20260901-002','Anita Devi','1996-08-20',30,'FEMALE','9845012345','Cross Road #3, Indiranagar Slum Colony','91-1234-5678-9012','','High Risk Pregnancy ANC','2026-09-03',1,4,1);
INSERT INTO "patients_patient" VALUES(3,'NC-20260901-003','Suresh Patil','1961-03-15',65,'MALE','9900112233','Ward 14 Slum Line, Ulsoor','91-9988-7766-5544','','Senior Citizen / Diabetic','2026-09-03',1,5,2);
INSERT INTO "patients_patient" VALUES(4,'NC-20260901-004','Demo Citizen 4',NULL,33,'MALE','9800000004','Ward Slum Area Pocket 5','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(5,'NC-20260901-005','Demo Citizen 5',NULL,35,'FEMALE','9800000005','Ward Slum Area Pocket 1','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(6,'NC-20260901-006','Demo Citizen 6',NULL,37,'MALE','9800000006','Ward Slum Area Pocket 2','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(7,'NC-20260901-007','Demo Citizen 7',NULL,39,'FEMALE','9800000007','Ward Slum Area Pocket 3','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(8,'NC-20260901-008','Demo Citizen 8',NULL,41,'MALE','9800000008','Ward Slum Area Pocket 4','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(9,'NC-20260901-009','Demo Citizen 9',NULL,43,'FEMALE','9800000009','Ward Slum Area Pocket 5','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(10,'NC-20260901-010','Demo Citizen 10',NULL,45,'MALE','9800000010','Ward Slum Area Pocket 1','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(11,'NC-20260901-011','Demo Citizen 11',NULL,47,'FEMALE','9800000011','Ward Slum Area Pocket 2','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(12,'NC-20260901-012','Demo Citizen 12',NULL,49,'MALE','9800000012','Ward Slum Area Pocket 3','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(13,'NC-20260901-013','Demo Citizen 13',NULL,51,'FEMALE','9800000013','Ward Slum Area Pocket 4','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(14,'NC-20260901-014','Demo Citizen 14',NULL,53,'MALE','9800000014','Ward Slum Area Pocket 5','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(15,'NC-20260901-015','Demo Citizen 15',NULL,55,'FEMALE','9800000015','Ward Slum Area Pocket 1','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(16,'NC-20260901-016','Demo Citizen 16',NULL,57,'MALE','9800000016','Ward Slum Area Pocket 2','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(17,'NC-20260901-017','Demo Citizen 17',NULL,59,'FEMALE','9800000017','Ward Slum Area Pocket 3','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(18,'NC-20260901-018','Demo Citizen 18',NULL,61,'MALE','9800000018','Ward Slum Area Pocket 4','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(19,'NC-20260901-019','Demo Citizen 19',NULL,63,'FEMALE','9800000019','Ward Slum Area Pocket 5','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(20,'NC-20260901-020','Demo Citizen 20',NULL,25,'MALE','9800000020','Ward Slum Area Pocket 1','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(21,'NC-20260901-021','Demo Citizen 21',NULL,27,'FEMALE','9800000021','Ward Slum Area Pocket 2','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(22,'NC-20260901-022','Demo Citizen 22',NULL,29,'MALE','9800000022','Ward Slum Area Pocket 3','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(23,'NC-20260901-023','Demo Citizen 23',NULL,31,'FEMALE','9800000023','Ward Slum Area Pocket 4','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(24,'NC-20260901-024','Demo Citizen 24',NULL,33,'MALE','9800000024','Ward Slum Area Pocket 5','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(25,'NC-20260901-025','Demo Citizen 25',NULL,35,'FEMALE','9800000025','Ward Slum Area Pocket 1','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(26,'NC-20260901-026','Demo Citizen 26',NULL,37,'MALE','9800000026','Ward Slum Area Pocket 2','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(27,'NC-20260901-027','Demo Citizen 27',NULL,39,'FEMALE','9800000027','Ward Slum Area Pocket 3','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(28,'NC-20260901-028','Demo Citizen 28',NULL,41,'MALE','9800000028','Ward Slum Area Pocket 4','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(29,'NC-20260901-029','Demo Citizen 29',NULL,43,'FEMALE','9800000029','Ward Slum Area Pocket 5','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(30,'NC-20260901-030','Demo Citizen 30',NULL,45,'MALE','9800000030','Ward Slum Area Pocket 1','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(31,'NC-20260901-031','Demo Citizen 31',NULL,47,'FEMALE','9800000031','Ward Slum Area Pocket 2','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(32,'NC-20260901-032','Demo Citizen 32',NULL,49,'MALE','9800000032','Ward Slum Area Pocket 3','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(33,'NC-20260901-033','Demo Citizen 33',NULL,51,'FEMALE','9800000033','Ward Slum Area Pocket 4','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
INSERT INTO "patients_patient" VALUES(34,'NC-20260901-034','Demo Citizen 34',NULL,53,'MALE','9800000034','Ward Slum Area Pocket 5','','','Slum Resident / Low Income Group','2026-09-03',1,7,5);
CREATE TABLE "pharmacy_inventorytransaction" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "transaction_type" varchar(30) NOT NULL, "quantity" integer NOT NULL, "reference_id" varchar(100) NOT NULL, "created_at" datetime NOT NULL, "created_by_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "batch_id" bigint NULL REFERENCES "pharmacy_medicinebatch" ("id") DEFERRABLE INITIALLY DEFERRED, "medicine_id" bigint NOT NULL REFERENCES "pharmacy_medicinemaster" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "pharmacy_inventorytransaction" VALUES(1,'DISPENSED',28,'PRESCR-1','2026-09-03 06:04:05.686763',7,7,1,1);
CREATE TABLE "pharmacy_medicinebatch" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "batch_number" varchar(50) NOT NULL, "supplier" varchar(100) NOT NULL, "received_date" date NOT NULL, "expiry_date" date NOT NULL, "quantity" integer NOT NULL, "unit_cost" decimal NOT NULL, "status" varchar(20) NOT NULL, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "medicine_id" bigint NOT NULL REFERENCES "pharmacy_medicinemaster" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "pharmacy_medicinebatch" VALUES(1,'BATCH-MET-2026A','KSMSCL (E-Aushada)','2026-09-03','2027-01-01',422,1.5,'ACTIVE',7,1);
INSERT INTO "pharmacy_medicinebatch" VALUES(2,'BATCH-MET-2026B','KSMSCL (E-Aushada)','2026-09-03','2027-08-29',800,1.5,'ACTIVE',7,1);
INSERT INTO "pharmacy_medicinebatch" VALUES(3,'BATCH-AML-2026X','KSMSCL (E-Aushada)','2026-09-03','2026-10-18',35,1.5,'LOW_STOCK',7,2);
INSERT INTO "pharmacy_medicinebatch" VALUES(4,'BATCH-PCM-2026P','KSMSCL (E-Aushada)','2026-09-03','2027-03-22',1200,1.5,'ACTIVE',7,3);
INSERT INTO "pharmacy_medicinebatch" VALUES(5,'BATCH-AMX-OLD','KSMSCL (E-Aushada)','2026-09-03','2026-08-19',40,1.5,'EXPIRED',7,4);
CREATE TABLE "pharmacy_medicinemaster" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "generic_name" varchar(150) NOT NULL, "brand_name" varchar(150) NOT NULL, "strength" varchar(50) NOT NULL, "dosage_form" varchar(50) NOT NULL, "unit" varchar(20) NOT NULL, "category" varchar(50) NOT NULL, "reorder_level" integer NOT NULL);
INSERT INTO "pharmacy_medicinemaster" VALUES(1,'Metformin HCl','Glycomet','500 mg','Tablet','Tablets','Anti-Diabetic',100);
INSERT INTO "pharmacy_medicinemaster" VALUES(2,'Amlodipine Besylate','Amlopres','5 mg','Tablet','Tablets','Anti-Hypertensive',100);
INSERT INTO "pharmacy_medicinemaster" VALUES(3,'Paracetamol','Dolo','650 mg','Tablet','Tablets','Analgesic / Antipyretic',200);
INSERT INTO "pharmacy_medicinemaster" VALUES(4,'Amoxicillin Trihydrate','Mox','500 mg','Capsule','Tablets','Antibiotic',100);
INSERT INTO "pharmacy_medicinemaster" VALUES(5,'Telmisartan','Telma','40 mg','Tablet','Tablets','Anti-Hypertensive',80);
CREATE TABLE "quality_biomedicalwastelog" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "date" date NOT NULL, "yellow_bag_kg" decimal NOT NULL, "red_bag_kg" decimal NOT NULL, "white_translucent_sharp_kg" decimal NOT NULL, "blue_box_glass_kg" decimal NOT NULL, "disposal_agency" varchar(150) NOT NULL, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "handed_over_by_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "quality_biomedicalwastelog" VALUES(1,'2026-09-03',3.2,2.1,0.6,1.5,'Authorized CBWTF Vendor',7,5);
CREATE TABLE "quality_qualitychecklist" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "inspection_date" date NOT NULL, "cleanliness_score" integer NOT NULL, "infection_control_passed" bool NOT NULL, "kayakalpa_audit_status" varchar(50) NOT NULL, "corrective_actions" text NOT NULL, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "inspected_by_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "quality_qualitychecklist" VALUES(1,'2026-09-03',96,1,'COMPLIANT','',7,2);
CREATE TABLE "referrals_followup" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "category" varchar(30) NOT NULL, "due_date" date NOT NULL, "status" varchar(20) NOT NULL, "notes" text NOT NULL, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "patient_id" bigint NOT NULL REFERENCES "patients_patient" ("id") DEFERRABLE INITIALLY DEFERRED, "visit_id" bigint NULL REFERENCES "visits_visit" ("id") DEFERRABLE INITIALLY DEFERRED, "referral_id" bigint NULL REFERENCES "referrals_referral" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "referrals_followup" VALUES(1,'REFERRAL','2026-09-17','PENDING','Review post-specialist referral response',7,1,1,1);
CREATE TABLE "referrals_referral" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "referral_id" varchar(50) NOT NULL UNIQUE, "reason" text NOT NULL, "clinical_summary" text NOT NULL, "required_service" varchar(100) NOT NULL, "urgency" varchar(20) NOT NULL, "referral_date" datetime NOT NULL, "status" varchar(30) NOT NULL, "destination_facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "patient_id" bigint NOT NULL REFERENCES "patients_patient" ("id") DEFERRABLE INITIALLY DEFERRED, "referring_doctor_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "source_facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "referrals_referral" VALUES(1,'REF-20260903-0001','Specialist evaluation for uncontrolled hypertension and diabetic review','52/M with BP 148/96, HbA1c 8.4%. Referred for secondary hospital cardiology consult.','Cardiology & Endocrine Review','HIGH','2026-09-03 06:04:05.688552','COMPLETED',2,1,4,7);
CREATE TABLE "referrals_referralresponse" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "specialist_findings" text NOT NULL, "treatment_summary" text NOT NULL, "return_advice" text NOT NULL, "responded_at" datetime NOT NULL, "hospital_doctor_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "referral_id" bigint NOT NULL UNIQUE REFERENCES "referrals_referral" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "referrals_referralresponse" VALUES(1,'Essential Hypertension with mild ECG changes. Diabetes mellitus uncontrolled.','Continue Metformin 500mg BD. Upgrade Amlodipine to 10mg OD. Added Telmisartan 40mg.','Patient stable. Return to Rural Clinic A4 for routine follow-up in 14 days.','2026-09-03 06:04:05.688552',3,1);
CREATE TABLE "surveillance_diseasecase" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "disease_name" varchar(100) NOT NULL, "report_date" date NOT NULL, "severity" varchar(20) NOT NULL, "status" varchar(20) NOT NULL, "notes" text NOT NULL, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "patient_id" bigint NOT NULL REFERENCES "patients_patient" ("id") DEFERRABLE INITIALLY DEFERRED, "ward_id" bigint NULL REFERENCES "geography_ward" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "surveillance_diseasecase" VALUES(1,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,1,5);
INSERT INTO "surveillance_diseasecase" VALUES(2,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(3,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(4,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(5,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(6,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(7,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(8,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(9,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(10,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(11,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(12,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(13,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(14,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
INSERT INTO "surveillance_diseasecase" VALUES(15,'Acute Pyrexia / Suspected Viral Fever','2026-09-03','MODERATE','CONFIRMED','Fever case reported during OPD',7,3,5);
CREATE TABLE "telemedicine_teleconsultation" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "teleconsult_id" varchar(50) NOT NULL UNIQUE, "specialty_required" varchar(100) NOT NULL, "scheduled_time" datetime NOT NULL, "status" varchar(20) NOT NULL, "clinical_notes" text NOT NULL, "specialist_advice" text NOT NULL, "created_at" datetime NOT NULL, "clinic_facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "hub_facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "patient_id" bigint NOT NULL REFERENCES "patients_patient" ("id") DEFERRABLE INITIALLY DEFERRED, "requesting_doctor_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "specialist_doctor_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED);
CREATE TABLE "triage_triagevitals" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "blood_pressure_systolic" integer NOT NULL, "blood_pressure_diastolic" integer NOT NULL, "pulse_bpm" integer NOT NULL, "temperature_f" decimal NOT NULL, "spo2_percent" integer NOT NULL, "respiratory_rate" integer NOT NULL, "height_cm" decimal NOT NULL, "weight_kg" decimal NOT NULL, "bmi" decimal NOT NULL, "blood_glucose_mgdl" integer NOT NULL, "high_bp_flag" bool NOT NULL, "high_glucose_flag" bool NOT NULL, "fever_flag" bool NOT NULL, "low_spo2_flag" bool NOT NULL, "pregnancy_high_risk_flag" bool NOT NULL, "emergency_flag" bool NOT NULL, "ncd_risk_flag" bool NOT NULL, "nurse_notes" text NOT NULL, "created_at" datetime NOT NULL, "nurse_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "patient_id" bigint NOT NULL REFERENCES "patients_patient" ("id") DEFERRABLE INITIALLY DEFERRED, "visit_id" bigint NOT NULL UNIQUE REFERENCES "visits_visit" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "triage_triagevitals" VALUES(1,148,96,84,99.1,98,18,168,78,27.6,185,1,1,0,0,0,0,1,'Patient presents with high BP and elevated blood sugar. Fast-tracked for doctor consultation.','2026-09-03 06:04:05.671666',5,1,1);
CREATE TABLE "visits_token" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "token_number" integer NOT NULL, "date" date NOT NULL, "priority" varchar(20) NOT NULL, "status" varchar(20) NOT NULL, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "visit_id" bigint NOT NULL UNIQUE REFERENCES "visits_visit" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "visits_token" VALUES(1,1,'2026-09-03','NORMAL','COMPLETED',7,1);
CREATE TABLE "visits_visit" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "visit_id" varchar(50) NOT NULL UNIQUE, "visit_date" datetime NOT NULL, "visit_type" varchar(40) NOT NULL, "status" varchar(30) NOT NULL, "chief_complaint" text NOT NULL, "assigned_doctor_id" bigint NULL REFERENCES "accounts_user" ("id") DEFERRABLE INITIALLY DEFERRED, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED, "patient_id" bigint NOT NULL REFERENCES "patients_patient" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "visits_visit" VALUES(1,'VIS-20260903-001','2026-09-03 06:04:05.671666','GENERAL_OPD','COMPLETED','Dizziness, severe fatigue, and blurred vision for 5 days',4,7,1);
CREATE TABLE "wellness_wellnesssession" ("id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, "session_type" varchar(50) NOT NULL, "instructor_name" varchar(150) NOT NULL, "session_date" date NOT NULL, "session_time" varchar(30) NOT NULL, "venue" varchar(150) NOT NULL, "participants_count" integer NOT NULL, "incentive_amount_rs" decimal NOT NULL, "notes" text NOT NULL, "facility_id" bigint NOT NULL REFERENCES "facilities_facility" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "wellness_wellnesssession" VALUES(1,'Yoga & Meditation','Guru Sri Anand (AYUSH Certified)','2026-09-01','07:00 AM - 08:00 AM','Varthur Clinic Courtyard',28,250,'',7);
CREATE INDEX "geography_district_state_id_37a7f3af" ON "geography_district" ("state_id");
CREATE INDEX "geography_zone_district_id_42e7146e" ON "geography_zone" ("district_id");
CREATE INDEX "geography_ward_zone_id_396ecac3" ON "geography_ward" ("zone_id");
CREATE INDEX "facilities_facility_district_id_6e35953c" ON "facilities_facility" ("district_id");
CREATE INDEX "facilities_facility_parent_facility_id_7856792e" ON "facilities_facility" ("parent_facility_id");
CREATE INDEX "facilities_facility_state_id_6446c57b" ON "facilities_facility" ("state_id");
CREATE INDEX "facilities_facility_ward_id_a6bd79f1" ON "facilities_facility" ("ward_id");
CREATE INDEX "facilities_facility_zone_id_3d093ccf" ON "facilities_facility" ("zone_id");
CREATE INDEX "facilities_facilityrelationship_destination_facility_id_5674a24a" ON "facilities_facilityrelationship" ("destination_facility_id");
CREATE INDEX "facilities_facilityrelationship_source_facility_id_11b1c441" ON "facilities_facilityrelationship" ("source_facility_id");
CREATE UNIQUE INDEX "django_content_type_app_label_model_76bd3d3b_uniq" ON "django_content_type" ("app_label", "model");
CREATE UNIQUE INDEX "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" ON "auth_group_permissions" ("group_id", "permission_id");
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE UNIQUE INDEX "auth_permission_content_type_id_codename_01ab375a_uniq" ON "auth_permission" ("content_type_id", "codename");
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "accounts_user_assigned_district_id_7173d217" ON "accounts_user" ("assigned_district_id");
CREATE INDEX "accounts_user_assigned_facility_id_7a453a02" ON "accounts_user" ("assigned_facility_id");
CREATE UNIQUE INDEX "accounts_user_groups_user_id_group_id_59c0b32f_uniq" ON "accounts_user_groups" ("user_id", "group_id");
CREATE INDEX "accounts_user_groups_user_id_52b62117" ON "accounts_user_groups" ("user_id");
CREATE INDEX "accounts_user_groups_group_id_bd11a704" ON "accounts_user_groups" ("group_id");
CREATE UNIQUE INDEX "accounts_user_user_permissions_user_id_permission_id_2ab516c2_uniq" ON "accounts_user_user_permissions" ("user_id", "permission_id");
CREATE INDEX "accounts_user_user_permissions_user_id_e4f0a161" ON "accounts_user_user_permissions" ("user_id");
CREATE INDEX "accounts_user_user_permissions_permission_id_113bb443" ON "accounts_user_user_permissions" ("permission_id");
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
CREATE INDEX "patients_household_ward_id_0638df5b" ON "patients_household" ("ward_id");
CREATE INDEX "patients_patient_district_id_b975898a" ON "patients_patient" ("district_id");
CREATE INDEX "patients_patient_registered_at_facility_id_61749ec5" ON "patients_patient" ("registered_at_facility_id");
CREATE INDEX "patients_patient_ward_id_3bafde89" ON "patients_patient" ("ward_id");
CREATE INDEX "alerts_alert_assigned_user_id_ff6c6d80" ON "alerts_alert" ("assigned_user_id");
CREATE INDEX "alerts_alert_facility_id_206bc61b" ON "alerts_alert" ("facility_id");
CREATE INDEX "alerts_alert_patient_id_c81ddaf7" ON "alerts_alert" ("patient_id");
CREATE INDEX "ars_arsmeeting_facility_id_a05b2657" ON "ars_arsmeeting" ("facility_id");
CREATE INDEX "ars_arsactionitem_meeting_id_77643095" ON "ars_arsactionitem" ("meeting_id");
CREATE INDEX "ars_arsmember_facility_id_999d8e92" ON "ars_arsmember" ("facility_id");
CREATE INDEX "audit_auditlog_facility_id_84ad76c4" ON "audit_auditlog" ("facility_id");
CREATE INDEX "audit_auditlog_user_id_c1cca96c" ON "audit_auditlog" ("user_id");
CREATE INDEX "visits_visit_assigned_doctor_id_9d8dce1d" ON "visits_visit" ("assigned_doctor_id");
CREATE INDEX "visits_visit_facility_id_79657c1c" ON "visits_visit" ("facility_id");
CREATE INDEX "visits_visit_patient_id_59dd1282" ON "visits_visit" ("patient_id");
CREATE INDEX "visits_token_facility_id_d297bdc0" ON "visits_token" ("facility_id");
CREATE INDEX "consultations_consultation_doctor_id_d309d94f" ON "consultations_consultation" ("doctor_id");
CREATE INDEX "consultations_consultation_facility_id_b6b8039d" ON "consultations_consultation" ("facility_id");
CREATE INDEX "consultations_consultation_patient_id_6a939c5c" ON "consultations_consultation" ("patient_id");
CREATE INDEX "consultations_prescription_doctor_id_b074e124" ON "consultations_prescription" ("doctor_id");
CREATE INDEX "consultations_prescription_facility_id_d8b4043d" ON "consultations_prescription" ("facility_id");
CREATE INDEX "consultations_prescription_patient_id_dd0d0cd5" ON "consultations_prescription" ("patient_id");
CREATE INDEX "consultations_prescriptionitem_prescription_id_ad06b8fb" ON "consultations_prescriptionitem" ("prescription_id");
CREATE INDEX "laboratory_laborder_consultation_id_d32bb9e8" ON "laboratory_laborder" ("consultation_id");
CREATE INDEX "laboratory_laborder_doctor_id_8d1ddec4" ON "laboratory_laborder" ("doctor_id");
CREATE INDEX "laboratory_laborder_facility_id_f3b4f167" ON "laboratory_laborder" ("facility_id");
CREATE INDEX "laboratory_laborder_patient_id_380de535" ON "laboratory_laborder" ("patient_id");
CREATE INDEX "laboratory_laborder_test_master_id_4fe1421d" ON "laboratory_laborder" ("test_master_id");
CREATE INDEX "laboratory_labresult_verified_by_id_26521670" ON "laboratory_labresult" ("verified_by_id");
CREATE INDEX "laboratory_labsample_collected_by_id_71e43204" ON "laboratory_labsample" ("collected_by_id");
CREATE INDEX "ncd_ncdrecord_facility_id_fd80b4d7" ON "ncd_ncdrecord" ("facility_id");
CREATE INDEX "ncd_ncdrecord_patient_id_35a791d5" ON "ncd_ncdrecord" ("patient_id");
CREATE INDEX "outreach_outreachactivity_facility_id_bf8fcbff" ON "outreach_outreachactivity" ("facility_id");
CREATE INDEX "outreach_outreachactivity_ward_id_2ff6a95b" ON "outreach_outreachactivity" ("ward_id");
CREATE INDEX "pharmacy_medicinebatch_facility_id_0db2eee2" ON "pharmacy_medicinebatch" ("facility_id");
CREATE INDEX "pharmacy_medicinebatch_medicine_id_669d3663" ON "pharmacy_medicinebatch" ("medicine_id");
CREATE INDEX "pharmacy_inventorytransaction_created_by_id_90432057" ON "pharmacy_inventorytransaction" ("created_by_id");
CREATE INDEX "pharmacy_inventorytransaction_facility_id_5927fd05" ON "pharmacy_inventorytransaction" ("facility_id");
CREATE INDEX "pharmacy_inventorytransaction_batch_id_50031ba5" ON "pharmacy_inventorytransaction" ("batch_id");
CREATE INDEX "pharmacy_inventorytransaction_medicine_id_c28f264a" ON "pharmacy_inventorytransaction" ("medicine_id");
CREATE INDEX "quality_biomedicalwastelog_facility_id_81f0011a" ON "quality_biomedicalwastelog" ("facility_id");
CREATE INDEX "quality_biomedicalwastelog_handed_over_by_id_79545b80" ON "quality_biomedicalwastelog" ("handed_over_by_id");
CREATE INDEX "quality_qualitychecklist_facility_id_db773f5b" ON "quality_qualitychecklist" ("facility_id");
CREATE INDEX "quality_qualitychecklist_inspected_by_id_9ee76009" ON "quality_qualitychecklist" ("inspected_by_id");
CREATE INDEX "referrals_referral_destination_facility_id_e184c186" ON "referrals_referral" ("destination_facility_id");
CREATE INDEX "referrals_referral_patient_id_e1ef9d2b" ON "referrals_referral" ("patient_id");
CREATE INDEX "referrals_referral_referring_doctor_id_9d8454b0" ON "referrals_referral" ("referring_doctor_id");
CREATE INDEX "referrals_referral_source_facility_id_12df277e" ON "referrals_referral" ("source_facility_id");
CREATE INDEX "referrals_followup_facility_id_a3128252" ON "referrals_followup" ("facility_id");
CREATE INDEX "referrals_followup_patient_id_11b057b7" ON "referrals_followup" ("patient_id");
CREATE INDEX "referrals_followup_visit_id_64852764" ON "referrals_followup" ("visit_id");
CREATE INDEX "referrals_followup_referral_id_0be803b9" ON "referrals_followup" ("referral_id");
CREATE INDEX "referrals_referralresponse_hospital_doctor_id_02779ea4" ON "referrals_referralresponse" ("hospital_doctor_id");
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
CREATE INDEX "surveillance_diseasecase_facility_id_c8260e33" ON "surveillance_diseasecase" ("facility_id");
CREATE INDEX "surveillance_diseasecase_patient_id_eddf8819" ON "surveillance_diseasecase" ("patient_id");
CREATE INDEX "surveillance_diseasecase_ward_id_2c45241e" ON "surveillance_diseasecase" ("ward_id");
CREATE INDEX "telemedicine_teleconsultation_clinic_facility_id_0976aa11" ON "telemedicine_teleconsultation" ("clinic_facility_id");
CREATE INDEX "telemedicine_teleconsultation_hub_facility_id_03278d51" ON "telemedicine_teleconsultation" ("hub_facility_id");
CREATE INDEX "telemedicine_teleconsultation_patient_id_aa98f935" ON "telemedicine_teleconsultation" ("patient_id");
CREATE INDEX "telemedicine_teleconsultation_requesting_doctor_id_b82cbea1" ON "telemedicine_teleconsultation" ("requesting_doctor_id");
CREATE INDEX "telemedicine_teleconsultation_specialist_doctor_id_afa1c3a5" ON "telemedicine_teleconsultation" ("specialist_doctor_id");
CREATE INDEX "triage_triagevitals_nurse_id_50ef15f5" ON "triage_triagevitals" ("nurse_id");
CREATE INDEX "triage_triagevitals_patient_id_7b341969" ON "triage_triagevitals" ("patient_id");
CREATE INDEX "wellness_wellnesssession_facility_id_5b47ba2e" ON "wellness_wellnesssession" ("facility_id");
DELETE FROM "sqlite_sequence";
INSERT INTO "sqlite_sequence" VALUES('django_migrations',39);
INSERT INTO "sqlite_sequence" VALUES('django_content_type',45);
INSERT INTO "sqlite_sequence" VALUES('auth_permission',180);
INSERT INTO "sqlite_sequence" VALUES('auth_group',0);
INSERT INTO "sqlite_sequence" VALUES('django_admin_log',0);
INSERT INTO "sqlite_sequence" VALUES('geography_state',1);
INSERT INTO "sqlite_sequence" VALUES('geography_district',2);
INSERT INTO "sqlite_sequence" VALUES('geography_zone',3);
INSERT INTO "sqlite_sequence" VALUES('geography_ward',5);
INSERT INTO "sqlite_sequence" VALUES('facilities_facility',13);
INSERT INTO "sqlite_sequence" VALUES('facilities_facilityrelationship',5);
INSERT INTO "sqlite_sequence" VALUES('accounts_user',8);
INSERT INTO "sqlite_sequence" VALUES('laboratory_labtestmaster',5);
INSERT INTO "sqlite_sequence" VALUES('pharmacy_medicinemaster',5);
INSERT INTO "sqlite_sequence" VALUES('pharmacy_medicinebatch',5);
INSERT INTO "sqlite_sequence" VALUES('patients_patient',34);
INSERT INTO "sqlite_sequence" VALUES('visits_visit',1);
INSERT INTO "sqlite_sequence" VALUES('visits_token',1);
INSERT INTO "sqlite_sequence" VALUES('triage_triagevitals',1);
INSERT INTO "sqlite_sequence" VALUES('consultations_consultation',1);
INSERT INTO "sqlite_sequence" VALUES('consultations_prescription',1);
INSERT INTO "sqlite_sequence" VALUES('consultations_prescriptionitem',2);
INSERT INTO "sqlite_sequence" VALUES('pharmacy_inventorytransaction',1);
INSERT INTO "sqlite_sequence" VALUES('laboratory_laborder',1);
INSERT INTO "sqlite_sequence" VALUES('laboratory_labsample',1);
INSERT INTO "sqlite_sequence" VALUES('laboratory_labresult',1);
INSERT INTO "sqlite_sequence" VALUES('referrals_referral',1);
INSERT INTO "sqlite_sequence" VALUES('referrals_referralresponse',1);
INSERT INTO "sqlite_sequence" VALUES('referrals_followup',1);
INSERT INTO "sqlite_sequence" VALUES('ncd_ncdrecord',2);
INSERT INTO "sqlite_sequence" VALUES('surveillance_diseasecase',15);
INSERT INTO "sqlite_sequence" VALUES('outreach_outreachactivity',1);
INSERT INTO "sqlite_sequence" VALUES('wellness_wellnesssession',1);
INSERT INTO "sqlite_sequence" VALUES('ars_arsmeeting',1);
INSERT INTO "sqlite_sequence" VALUES('ars_arsmember',2);
INSERT INTO "sqlite_sequence" VALUES('ars_arsactionitem',1);
INSERT INTO "sqlite_sequence" VALUES('quality_qualitychecklist',1);
INSERT INTO "sqlite_sequence" VALUES('quality_biomedicalwastelog',1);
INSERT INTO "sqlite_sequence" VALUES('alerts_alert',3);
INSERT INTO "sqlite_sequence" VALUES('integrations_integrationconfiguration',4);
INSERT INTO "sqlite_sequence" VALUES('compliance_complianceitem',2);
INSERT INTO "sqlite_sequence" VALUES('audit_auditlog',1);
COMMIT;
