# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chief_complaint', models.TextField()),
                ('clinical_history', models.TextField(blank=True)),
                ('clinical_assessment', models.TextField(blank=True)),
                ('diagnosis_code', models.CharField(default='E11', max_length=50)),
                ('diagnosis_name', models.CharField(default='Type 2 Diabetes Mellitus / Essential Hypertension', max_length=200)),
                ('treatment_plan', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('clinical_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='patients.patient')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consultation', to='visits.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='consultations.consultation')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=150)),
                ('dosage', models.CharField(default='1-0-1 After Food', max_length=50)),
                ('frequency', models.CharField(default='Twice Daily', max_length=50)),
                ('duration_days', models.IntegerField(default=7)),
                ('quantity', models.IntegerField(default=14)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='consultations.prescription')),
            ],
        ),
    ]
