# Generated by Django 4.2.30 on 2026-09-21 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_purchaseorder_approved_at_purchaseorder_approved_by_and_more'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription_items', to='pharmacy.medicinemaster'),
        ),
    ]
