# Generated by Django 6.1.1 on 2026-09-24 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_prescription_rejection_reason_and_more'),
        ('pharmacy', '0004_purchaseorder_approved_at_purchaseorder_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='dispensed_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='medicine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicinemaster'),
        ),
    ]
