# Generated by Django 4.2.30 on 2026-09-22 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0003_populate_prescriptionitem_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_prescriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='dispensed_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Pharmacist Verification'), ('VERIFIED', 'Verified by Pharmacist'), ('ON_HOLD', 'Clinical Hold (Query Pending)'), ('REJECTED', 'Rejected by Pharmacist'), ('PARTIALLY_DISPENSED', 'Partially Dispensed'), ('DISPENSED', 'Fully Dispensed'), ('CANCELLED', 'Cancelled by Prescriber / Admin'), ('EXPIRED', 'Prescription Validity Expired'), ('ACTIVE', 'Active (Legacy Dispensable Status)')], default='PENDING_VERIFICATION', max_length=30),
        ),
        migrations.AlterField(
            model_name='prescriptionitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Dispensation'), ('PARTIALLY_DISPENSED', 'Partially Dispensed'), ('DISPENSED', 'Fully Dispensed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
