# Generated by Django 4.2.30 on 2026-09-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_person_rolemaster_staffprofile_staffroleassignment_and_more'),
        ('consultations', '0004_prescription_rejection_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd10_code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('is_notifiable', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diagnosis_masters',
            },
        ),
        migrations.AddField(
            model_name='consultation',
            name='consultation_sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='consultation',
            name='doctor_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='conducted_consultations', to='accounts.staffprofile'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consultation_sequence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prescription',
            name='doctor_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='authored_prescriptions', to='accounts.staffprofile'),
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_type', models.CharField(choices=[('ADMISSION', 'Admission'), ('WORKING', 'Working'), ('DISCHARGE', 'Discharge')], default='WORKING', max_length=20)),
                ('certainty', models.CharField(choices=[('PROVISIONAL', 'Provisional'), ('CONFIRMED', 'Confirmed')], default='PROVISIONAL', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='consultations.consultation')),
                ('diagnosis_master', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='diagnoses', to='consultations.diagnosismaster')),
            ],
            options={
                'db_table': 'diagnoses',
            },
        ),
    ]
