# Generated by Django 4.2.30 on 2026-09-23 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0004_facilitydailycounter'),
        ('consultations', '0005_diagnosismaster_consultation_consultation_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='visits.visit'),
        ),
    ]
