# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_id', models.CharField(max_length=50, unique=True)),
                ('head_name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('members_count', models.IntegerField(default=4)),
                ('vulnerable_category', models.CharField(default='Slum Household', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geography.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(default=30)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('mobile', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('ABHA_ID_DEMO', models.CharField(blank=True, max_length=50)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('vulnerability_information', models.CharField(default='Slum Resident / Low Income Group', max_length=100)),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='geography.district')),
                ('registered_at_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to='facilities.facility')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='geography.ward')),
            ],
        ),
    ]
