# Generated by Django 6.1.1 on 2026-09-17 06:37

import apps.patients.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facilitybedallocation_facilitybedcapacity_and_more'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('MEDICAL_RECORD', 'Medical Record'), ('LAB_REPORT', 'Lab Report'), ('PRESCRIPTION', 'Prescription'), ('DISCHARGE_SUMMARY', 'Discharge Summary'), ('REFERRAL_DOCUMENT', 'Referral Document'), ('OTHER', 'Other Medical Document')], default='OTHER', max_length=50)),
                ('file', models.FileField(upload_to=apps.patients.models.patient_document_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('document_date', models.DateField(default=datetime.date.today)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_documents', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_patient_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-document_date', '-uploaded_at'],
            },
        ),
    ]
