# Generated by Django 4.2.30 on 2026-09-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_person_rolemaster_staffprofile_staffroleassignment_and_more'),
        ('patients', '0002_patientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='registered_patients', to='accounts.person'),
        ),
    ]
