# Generated by Django 4.2.30 on 2026-09-28 15:17

from django.db import migrations, models


def populate_normalized_fields(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    for p in Patient.objects.all():
        raw_name = p.name or ""
        raw_mobile = p.mobile or ""
        p.normalized_name = " ".join(raw_name.lower().strip().split())
        m = raw_mobile.strip().replace(" ", "").replace("-", "")
        if m.startswith("+91"):
            m = m[3:]
        elif m.startswith("91") and len(m) == 12:
            m = m[2:]
        elif m.startswith("0") and len(m) == 11:
            m = m[1:]
        p.normalized_mobile = m
        p.save(update_fields=['normalized_name', 'normalized_mobile'])


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='normalized_mobile',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='normalized_name',
            field=models.CharField(blank=True, db_index=True, default='', max_length=150),
        ),
        migrations.RunPython(populate_normalized_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(condition=models.Q(('registered_at_facility__isnull', False)), fields=('registered_at_facility', 'normalized_name', 'normalized_mobile'), name='unique_patient_facility_normalized_identity'),
        ),
    ]
