# Generated by Django 4.2.30 on 2026-09-23 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_servicemaster_facilityservice_department'),
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, default='', max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('aadhaar_hash', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
        migrations.CreateModel(
            name='RoleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'role_masters',
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('medical_council_reg_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(choices=[('PROBATION', 'Probation'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('RETIRED', 'Retired'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staff_members', to='facilities.department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staff_profiles', to='accounts.person')),
            ],
            options={
                'db_table': 'staff_profiles',
            },
        ),
        migrations.CreateModel(
            name='StaffRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staff_assignments', to='accounts.rolemaster')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='role_assignments', to='accounts.staffprofile')),
            ],
            options={
                'db_table': 'staff_role_assignments',
            },
        ),
        migrations.CreateModel(
            name='StaffFacilityAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('effective_from', models.DateField(default=datetime.date.today)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staff_facility_assignments', to='facilities.department')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='staff_facility_assignments', to='facilities.facility')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='facility_assignments', to='accounts.staffprofile')),
            ],
            options={
                'db_table': 'staff_facility_assignments',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='staff_profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='user_account', to='accounts.staffprofile'),
        ),
        migrations.AddConstraint(
            model_name='staffroleassignment',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='chk_staff_role_dates'),
        ),
        migrations.AddConstraint(
            model_name='stafffacilityassignment',
            constraint=models.CheckConstraint(check=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='chk_staff_facility_dates'),
        ),
    ]
