# Generated by Django 4.2.30 on 2026-09-28 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_person_rolemaster_staffprofile_staffroleassignment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('display_name', models.CharField(blank=True, default='', max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('domain', models.CharField(db_index=True, max_length=50)),
                ('action', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'permission_masters',
                'ordering': ['domain', 'code'],
            },
        ),
        migrations.AlterModelOptions(
            name='rolemaster',
            options={'ordering': ['code']},
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='is_system_role',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='scope_level',
            field=models.CharField(choices=[('GLOBAL', 'Global'), ('DISTRICT', 'District'), ('FACILITY', 'Facility')], default='FACILITY', max_length=20),
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rolemaster',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DISTRICT_OFFICER', 'District Officer'), ('HOSPITAL_ADMIN', 'Hospital Administrator'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('COMPOUNDER', 'Compounder'), ('LAB_TECHNICIAN', 'Lab Technician'), ('PHARMACIST', 'Pharmacist')], default='DOCTOR', max_length=30),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='accounts.permissionmaster')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.rolemaster')),
            ],
            options={
                'db_table': 'role_permissions',
            },
        ),
        migrations.AddField(
            model_name='rolemaster',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='roles', through='accounts.RolePermission', to='accounts.permissionmaster'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'is_active'], name='idx_role_perm_active'),
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['permission', 'is_active'], name='idx_perm_role_active'),
        ),
        migrations.AddConstraint(
            model_name='rolepermission',
            constraint=models.UniqueConstraint(fields=('role', 'permission'), name='uniq_role_permission'),
        ),
    ]
