# Generated by Django 4.2.30 on 2026-09-28 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_servicemaster_facilityservice_department'),
        ('accounts', '0004_permissionmaster_alter_rolemaster_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffroleassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_staff_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='staffroleassignment',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='staff_role_assignments', to='facilities.facility'),
        ),
        migrations.AddField(
            model_name='staffroleassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TRANSFER_PENDING', 'Transfer Pending'), ('DEACTIVATED', 'Deactivated'), ('PROBATION', 'Probation'), ('RETIRED', 'Retired'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='staffroleassignment',
            index=models.Index(fields=['staff', 'is_active', 'effective_from'], name='idx_staff_role_active'),
        ),
    ]
