# Generated by Django 4.2.30 on 2026-09-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_staffroleassignment_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(choices=[('INVITED', 'Invited'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TRANSFER_PENDING', 'Transfer Pending'), ('DEACTIVATED', 'Deactivated')], default='ACTIVE', max_length=20),
        ),
    ]
