# Generated by Django 4.2.30 on 2026-09-30 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_staffprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('DISTRICT_OFFICER', 'District Officer'), ('HOSPITAL_ADMIN', 'Hospital Administrator'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('COMPOUNDER', 'Compounder'), ('LAB_TECHNICIAN', 'Lab Technician'), ('PHARMACIST', 'Pharmacist'), ('INVENTORY', 'Inventory Manager')], default='DOCTOR', max_length=30),
        ),
    ]
