# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_id', models.CharField(max_length=50, unique=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('visit_type', models.CharField(default='GENERAL_OPD', max_length=40)),
                ('status', models.CharField(choices=[('WAITING', 'Waiting for Triage'), ('TRIAGED', 'Ready for Doctor'), ('IN_CONSULTATION', 'In Consultation'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=30)),
                ('chief_complaint', models.TextField(blank=True)),
                ('assigned_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal Queue'), ('EMERGENCY', 'Emergency Priority'), ('MATERNAL', 'Maternal / High-Risk'), ('SENIOR_CITIZEN', 'Senior Citizen')], default='NORMAL', max_length=20)),
                ('status', models.CharField(default='WAITING', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='visits.visit')),
            ],
        ),
    ]
