# Generated by Django 6.1.1 on 2026-09-16 10:05

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facilitybedallocation_facilitybedcapacity_and_more'),
        ('visits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('queue', models.CharField(max_length=30)),
                ('performed_by_role', models.CharField(blank=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='token',
            options={'ordering': ['date', 'token_number']},
        ),
        migrations.AlterModelOptions(
            name='visit',
            options={'ordering': ['-opd_date', 'arrival_time']},
        ),
        migrations.AddField(
            model_name='visit',
            name='arrival_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='visit',
            name='completed_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='consultation_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='consultation_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='current_queue',
            field=models.CharField(choices=[('TRIAGE', 'Nurse Triage Queue'), ('DOCTOR', 'Doctor Consultation Queue'), ('LAB', 'Laboratory Queue'), ('PHARMACY', 'Pharmacy Dispensing Queue'), ('COMPLETED', 'Completed Visit')], default='TRIAGE', max_length=30),
        ),
        migrations.AddField(
            model_name='visit',
            name='opd_date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='visit',
            name='priority',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency Priority 🚨'), ('HIGH', 'High Priority'), ('NORMAL', 'Normal Queue')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='visit',
            name='triage_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='triage_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='token',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='token',
            name='priority',
            field=models.CharField(choices=[('EMERGENCY', 'Emergency Priority 🚨'), ('HIGH', 'High Priority'), ('NORMAL', 'Normal Queue')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='token',
            name='status',
            field=models.CharField(default='WAITING', max_length=30),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_TRIAGE', 'Waiting for Triage'), ('IN_TRIAGE', 'In Triage'), ('TRIAGED', 'Triaged / Ready for Doctor'), ('WAITING_FOR_DOCTOR', 'Waiting for Doctor'), ('IN_CONSULTATION', 'In Consultation'), ('LAB_PENDING', 'Lab Pending'), ('LAB_IN_PROGRESS', 'Lab Test In Progress'), ('LAB_COMPLETED', 'Lab Test Completed'), ('WAITING_FOR_PHARMACY', 'Waiting for Pharmacy'), ('IN_PHARMACY', 'In Pharmacy Dispensing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='WAITING_FOR_TRIAGE', max_length=30),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('facility', 'date', 'token_number'), name='unique_facility_opd_date_token'),
        ),
        migrations.AddField(
            model_name='visitstatushistory',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visitstatushistory',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='visits.visit'),
        ),
    ]
