# Generated by Django 4.2.30 on 2026-09-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_visitstatushistory_alter_token_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('WAITING_FOR_TRIAGE', 'Waiting for Triage'), ('IN_TRIAGE', 'In Triage'), ('TRIAGED', 'Triaged / Ready for Doctor'), ('WAITING_FOR_DOCTOR', 'Waiting for Doctor'), ('IN_CONSULTATION', 'In Consultation'), ('WAITING_FOR_LAB', 'Waiting for Lab Results'), ('LAB_PENDING', 'Lab Pending'), ('LAB_IN_PROGRESS', 'Lab Test In Progress'), ('LAB_COMPLETED', 'Lab Test Completed'), ('DOCTOR_REVIEW', 'Doctor Review (Lab Completed)'), ('WAITING_FOR_PHARMACY', 'Waiting for Pharmacy'), ('IN_PHARMACY', 'In Pharmacy Dispensing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NO_SHOW', 'No Show')], default='WAITING_FOR_TRIAGE', max_length=30),
        ),
    ]
