# Generated by Django 4.2.30 on 2026-09-23 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_servicemaster_facilityservice_department'),
        ('visits', '0003_alter_visit_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityDailyCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_date', models.DateField(default=datetime.date.today)),
                ('counter_type', models.CharField(default='OPD', max_length=20)),
                ('last_token_number', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daily_counters', to='facilities.facility')),
            ],
            options={
                'db_table': 'facility_daily_counters',
                'unique_together': {('facility', 'counter_date', 'counter_type')},
            },
        ),
    ]
