# Generated by Django 6.1.1 on 2026-09-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=150)),
                ('status', models.CharField(default='MOCK', max_length=20)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(default='SUCCESS', max_length=30)),
                ('notes', models.TextField(default='Demo mock integration - local simulation mode. No external APIs connected.')),
            ],
        ),
    ]
