# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generic_name', models.CharField(max_length=150)),
                ('brand_name', models.CharField(blank=True, max_length=150)),
                ('strength', models.CharField(default='500 mg', max_length=50)),
                ('dosage_form', models.CharField(default='Tablet', max_length=50)),
                ('unit', models.CharField(default='Tablets', max_length=20)),
                ('category', models.CharField(default='Essential Medicines', max_length=50)),
                ('reorder_level', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('supplier', models.CharField(default='KSMSCL (E-Aushada)', max_length=100)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('quantity', models.IntegerField(default=500)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=1.5, max_digits=8)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_batches', to='facilities.facility')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='pharmacy.medicinemaster')),
            ],
            options={
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('RECEIVED', 'Received Stock'), ('ISSUED', 'Issued to Sub-Store'), ('DISPENSED', 'Dispensed to Patient'), ('TRANSFERRED', 'Transferred to Facility'), ('DAMAGED', 'Damaged / Wastage'), ('EXPIRED', 'Expired Stock'), ('ADJUSTMENT', 'Stock Audit Adjustment')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacy.medicinebatch')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicinemaster')),
            ],
        ),
    ]
