# Generated by Django 6.1.1 on 2026-09-17 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_inventorytransaction_notes_medicinebatch_mfg_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicinemaster',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-order_date', '-id']},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['-created_at']},
        ),
    ]
