# Generated by Django 4.2.30 on 2026-09-22 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_prescription_rejection_reason_and_more'),
        ('facilities', '0002_facilitybedallocation_facilitybedcapacity_and_more'),
        ('patients', '0002_patientdocument'),
        ('visits', '0003_alter_visit_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0004_purchaseorder_approved_at_purchaseorder_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='after_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='before_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='destination_after_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='destination_before_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='destination_bucket',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='prescription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.prescription'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.prescriptionitem'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='source_after_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='source_before_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='source_bucket',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visits.visit'),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='available_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='damaged_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='disposed_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='quarantined_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicinebatch',
            name='recalled_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='antibiotic',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='aware_category',
            field=models.CharField(blank=True, choices=[('ACCESS', 'Access'), ('WATCH', 'Watch'), ('RESERVE', 'Reserve'), ('NONE', 'Not an Antibiotic'), ('UNKNOWN', 'Unclassified')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='cold_chain_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='essential_medicine',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='high_alert',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='nlem_reference',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='prescription_required',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='regulatory_schedule',
            field=models.CharField(blank=True, choices=[('SCHEDULE_H', 'Schedule H'), ('SCHEDULE_H1', 'Schedule H1'), ('SCHEDULE_X', 'Schedule X'), ('SCHEDULE_G', 'Schedule G'), ('OTC', 'Over the Counter (OTC)'), ('GENERAL', 'General Sales'), ('UNKNOWN', 'Unclassified / Verification Required')], default='UNKNOWN', max_length=30),
        ),
        migrations.AddField(
            model_name='medicinemaster',
            name='route',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('PURCHASE_RECEIVED', 'Stock Received via Accepted GRN (+)'), ('DISPENSED', 'Medication Dispensed to Patient (-)'), ('RETURN_APPROVED', 'Customer Return Approved & Restored to Usable Stock (+)'), ('RETURN_QUARANTINED', 'Customer Return Routed to Quarantine (Bucket Transfer)'), ('RETURN_DISPOSED', 'Customer Return Routed to Condemnation (-)'), ('ADJUSTMENT_INCREASE', 'Stock Count Audit Positive Adjustment (+)'), ('ADJUSTMENT_DECREASE', 'Stock Count Audit Negative Adjustment (-)'), ('QUARANTINE_HOLD', 'Stock Moved from Available to Quarantine (Bucket Transfer)'), ('QUARANTINE_RELEASE', 'Stock Released from Quarantine to Available (Bucket Transfer)'), ('RECALL_HOLD', 'Stock Moved from Available to Recalled Bucket (Bucket Transfer)'), ('RECALL_RELEASE', 'Recalled Stock Cleared by Regulatory Authority (Bucket Transfer)'), ('DISPOSAL_DESTROYED', 'Condemned Stock Destroyed / Incinerated (-)'), ('DAMAGE_RECORDED', 'Damaged Stock Moved from Available Bucket (Bucket Transfer)'), ('TRANSFERRED_IN', 'Inter-Facility Stock Inflow (+)'), ('TRANSFERRED_OUT', 'Inter-Facility Stock Outflow (-)'), ('RETURNED', 'Returned Stock (Legacy)'), ('ADJUSTMENT', 'Stock Audit Adjustment (Legacy)'), ('DAMAGED', 'Damaged / Wastage (Legacy)'), ('EXPIRED', 'Expired Stock (Legacy)'), ('ISSUED', 'Issued to Sub-Store (Legacy)'), ('TRANSFERRED', 'Transferred to Facility (Legacy)')], max_length=30),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available (Operational)'), ('QUARANTINED', 'Quarantined (Quality / Investigation Hold)'), ('RECALLED', 'Recalled (Regulatory Recall Hold)'), ('DAMAGED', 'Damaged (Condemned / Spoilage)'), ('DISPOSED', 'Disposed (Formally Destroyed / Incinerated)'), ('EXHAUSTED', 'Stock Exhausted (Zero Physical Quantity)'), ('ACTIVE', 'Active (Legacy Alias for Available)'), ('LOW_STOCK', 'Low Stock (Legacy Alias for Available)'), ('EXPIRING_SOON', 'Expiring Soon (Legacy Alias for Available)'), ('EXPIRED', 'Expired (Legacy Alias)')], default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicinebatch',
            name='supplier',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PatientCounselling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counselled_at', models.DateTimeField(auto_now_add=True)),
                ('dose_explained', models.BooleanField(blank=True, default=None, null=True)),
                ('frequency_explained', models.BooleanField(blank=True, default=None, null=True)),
                ('duration_explained', models.BooleanField(blank=True, default=None, null=True)),
                ('food_instructions_given', models.BooleanField(blank=True, default=None, null=True)),
                ('storage_explained', models.BooleanField(blank=True, default=None, null=True)),
                ('warning_signs_explained', models.BooleanField(blank=True, default=None, null=True)),
                ('adherence_counselled', models.BooleanField(blank=True, default=None, null=True)),
                ('counselling_notes', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_records', to='patients.patient')),
                ('pharmacist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_counselling', to=settings.AUTH_USER_MODEL)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='counselling_record', to='consultations.prescription')),
            ],
            options={
                'ordering': ['-counselled_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(max_length=50, unique=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft Inspection'), ('ACCEPTED', 'Fully Accepted & Taken into Stock'), ('PARTIAL_ACCEPTANCE', 'Partially Accepted with Rejections'), ('REJECTED', 'Entire Shipment Rejected')], default='ACCEPTED', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='facilities.facility')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='pharmacy.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_grns', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50)),
                ('mfg_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('ordered_quantity', models.IntegerField()),
                ('received_quantity', models.IntegerField()),
                ('rejected_quantity', models.IntegerField(default=0)),
                ('rejection_reason', models.TextField(blank=True)),
                ('accepted_quantity', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('grn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.goodsreceiptnote')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy.medicinemaster')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grn_items', to='pharmacy.purchaseorderitem')),
            ],
        ),
        migrations.CreateModel(
            name='DispensationReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=50, unique=True)),
                ('returned_quantity', models.IntegerField()),
                ('return_reason', models.TextField()),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('assessment_status', models.CharField(choices=[('PENDING_ASSESSMENT', 'Pending Pharmacist Assessment'), ('ASSESSED', 'Assessment Completed')], default='PENDING_ASSESSMENT', max_length=30)),
                ('condition_intact', models.BooleanField(default=None, null=True)),
                ('packaging_sealed', models.BooleanField(default=None, null=True)),
                ('storage_valid', models.BooleanField(default=None, null=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('disposition', models.CharField(choices=[('PENDING', 'Pending Disposition'), ('APPROVED_FOR_STOCK', 'Approved for Stock Restoration (+)'), ('QUARANTINE', 'Quarantined for Investigation (Bucket Transfer)'), ('DISPOSAL', 'Condemned for Disposal (-)')], default='PENDING', max_length=30)),
                ('assessment_notes', models.TextField(blank=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessed_returns', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='pharmacy.medicinebatch')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensation_returns', to='facilities.facility')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='consultations.prescription')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='consultations.prescriptionitem')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-returned_at'],
            },
        ),
        migrations.CreateModel(
            name='ColdChainLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_location', models.CharField(default='Pharmacy Refrigerator', max_length=100)),
                ('min_temp_celsius', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True)),
                ('max_temp_celsius', models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True)),
                ('recorded_temp_celsius', models.DecimalField(decimal_places=1, max_digits=4)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('NORMAL', 'Normal Storage Temperature'), ('EXCURSION', 'Temperature Excursion Alert'), ('UNCONFIGURED_RANGE', 'Temperature Logged — Storage Range Not Configured')], default='UNCONFIGURED_RANGE', max_length=30)),
                ('corrective_action', models.TextField(blank=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cold_chain_logs', to='facilities.facility')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cold_chain_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchRecall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recall_number', models.CharField(max_length=50, unique=True)),
                ('recall_reference', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('recalled_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('INITIATED', 'Recall Initiated / Active Hold'), ('HELD_IN_QUARANTINE', 'Stock Held in Quarantine'), ('RELEASED', 'Recall Cleared / Released by Authority'), ('DISPOSED', 'Recalled Stock Condemned & Destroyed')], default='INITIATED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recalls', to='pharmacy.medicinebatch')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_recalls', to='facilities.facility')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_recalls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
