# Generated by Django 4.2.30 on 2026-09-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_pharmacy_hardening_data_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='accepted_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='rejected_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
