# Generated by Django 4.2.30 on 2026-09-23 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_diagnosismaster_consultation_consultation_sequence_and_more'),
        ('facilities', '0003_servicemaster_facilityservice_department'),
        ('accounts', '0003_person_rolemaster_staffprofile_staffroleassignment_and_more'),
        ('pharmacy', '0008_reconcile_procurement_demo_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensation_number', models.CharField(max_length=50, unique=True)),
                ('dispensed_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('dispensed_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dispensations', to='accounts.staffprofile')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dispensations', to='facilities.facility')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dispensations', to='consultations.prescription')),
            ],
            options={
                'db_table': 'dispensations',
            },
        ),
        migrations.CreateModel(
            name='InventoryLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE_RECEIPT', 'Purchase Receipt'), ('DISPENSE', 'Dispense'), ('DISPENSE_REVERSAL', 'Dispense Reversal'), ('TRANSFER_OUT', 'Transfer Out'), ('TRANSFER_IN', 'Transfer In'), ('DAMAGE_WRITEOFF', 'Damage Writeoff'), ('EXPIRED_WRITEOFF', 'Expired Writeoff'), ('AUDIT_CORRECTION', 'Audit Correction')], max_length=30)),
                ('quantity_delta', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('reference_entity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_entity_id', models.BigIntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('transaction_timestamp', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ledger_entries', to='pharmacy.medicinebatch')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='inventory_ledger_entries', to='facilities.facility')),
                ('performed_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='performed_inventory_movements', to='accounts.staffprofile')),
            ],
            options={
                'db_table': 'inventory_ledgers',
            },
        ),
        migrations.CreateModel(
            name='DispensationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.IntegerField()),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dispensation_items', to='pharmacy.medicinebatch')),
                ('dispensation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pharmacy.dispensation')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dispensation_items', to='consultations.prescriptionitem')),
            ],
            options={
                'db_table': 'dispensation_items',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_tier', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], max_length=20)),
                ('remarks', models.TextField(blank=True, default='')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approver_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='po_approvals', to='accounts.staffprofile')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='pharmacy.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_order_approvals',
                'unique_together': {('purchase_order', 'approval_tier')},
            },
        ),
        migrations.AddConstraint(
            model_name='inventoryledger',
            constraint=models.CheckConstraint(check=models.Q(('balance_after__gte', 0)), name='chk_ledger_balance'),
        ),
        migrations.AddConstraint(
            model_name='dispensationitem',
            constraint=models.CheckConstraint(check=models.Q(('quantity_dispensed__gt', 0)), name='chk_disp_items_qty'),
        ),
    ]
