# Generated by Django 6.1.1 on 2026-10-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_weight_kg', models.DecimalField(decimal_places=2, default=3.1, max_digits=4)),
                ('immunization_status', models.CharField(default='UP_TO_DATE', max_length=50)),
                ('sam_mam_status', models.CharField(default='NORMAL', max_length=30)),
                ('growth_chart_status', models.CharField(default='GREEN_ZONE', max_length=30)),
            ],
        ),
    ]
