# Generated by Django 6.1.1 on 2026-10-06 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('child', '0001_initial'),
        ('maternal', '0001_initial'),
        ('patients', '0002_patientdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='childrecord',
            name='maternal_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='maternal.maternalrecord'),
        ),
        migrations.AddField(
            model_name='childrecord',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_records', to='patients.patient'),
        ),
    ]
