# Generated by Django 6.1.1 on 2026-10-06 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patientdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaternalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anc_number', models.CharField(max_length=50, unique=True)),
                ('lmp_date', models.DateField()),
                ('edd_date', models.DateField()),
                ('high_risk_flag', models.BooleanField(default=False)),
                ('high_risk_reason', models.CharField(blank=True, max_length=200)),
                ('anc_checkups_count', models.IntegerField(default=1)),
                ('tt_vaccine_given', models.BooleanField(default=True)),
                ('ifa_tablets_issued', models.BooleanField(default=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maternal_records', to='patients.patient')),
            ],
        ),
    ]
