# Generated by Django 6.1.1 on 2026-09-03 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_id', models.CharField(max_length=50, unique=True)),
                ('requirement_text', models.TextField()),
                ('source_document', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=50)),
                ('application_module', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('FULLY_COVERED', 'Fully Covered'), ('PARTIALLY_COVERED', 'Partially Covered'), ('NOT_IMPLEMENTED', 'Not Implemented'), ('OUT_OF_DIGITAL_SCOPE', 'Out of Digital Scope')], default='FULLY_COVERED', max_length=30)),
                ('explanation', models.TextField()),
            ],
        ),
    ]
