# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teleconsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teleconsult_id', models.CharField(max_length=50, unique=True)),
                ('specialty_required', models.CharField(default='General Medicine / Cardiology', max_length=100)),
                ('scheduled_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', max_length=20)),
                ('clinical_notes', models.TextField(blank=True)),
                ('specialist_advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clinic_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsult_requests', to='facilities.facility')),
                ('hub_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleconsult_hubs', to='facilities.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('requesting_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teleconsult_requests', to=settings.AUTH_USER_MODEL)),
                ('specialist_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teleconsult_responses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
