# Generated by Django 6.1.1 on 2026-09-03 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARSMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField()),
                ('chairperson_name', models.CharField(max_length=150)),
                ('attendees_count', models.IntegerField(default=7)),
                ('agenda', models.TextField()),
                ('proceedings_summary', models.TextField()),
                ('untied_funds_spent_rs', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('signed_by_chairman', models.BooleanField(default=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
            ],
        ),
        migrations.CreateModel(
            name='ARSActionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_description', models.TextField()),
                ('responsible_person', models.CharField(max_length=150)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_items', to='ars.arsmeeting')),
            ],
        ),
        migrations.CreateModel(
            name='ARSMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('designation', models.CharField(max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ars_members', to='facilities.facility')),
            ],
        ),
    ]
