# Generated by Django 4.2.30 on 2026-09-22 05:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_alter_visit_status'),
        ('facilities', '0002_facilitybedallocation_facilitybedcapacity_and_more'),
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='visits.visit'),
        ),
        migrations.CreateModel(
            name='LabToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.IntegerField()),
                ('token_code', models.CharField(max_length=50)),
                ('date', models.DateField(db_index=True, default=datetime.date.today)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('IN_PROGRESS', 'Sample Collected / In Progress'), ('COMPLETED', 'Completed & Verified')], default='ORDERED', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tokens', to='facilities.facility')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tokens', to='visits.visit')),
            ],
            options={
                'ordering': ['date', 'token_number'],
            },
        ),
        migrations.AddField(
            model_name='laborder',
            name='lab_token',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='laboratory.labtoken'),
        ),
        migrations.AddConstraint(
            model_name='labtoken',
            constraint=models.UniqueConstraint(fields=('facility', 'date', 'token_number'), name='unique_facility_lab_date_token'),
        ),
    ]
