# Generated by Django 6.1.1 on 2026-09-21 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
        ('visits', '0002_visitstatushistory_alter_token_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laborder',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='visits.visit'),
        ),
    ]
