# Generated by Django 4.2.30 on 2026-09-23 18:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_servicemaster_facilityservice_department'),
        ('visits', '0004_facilitydailycounter'),
        ('accounts', '0003_person_rolemaster_staffprofile_staffroleassignment_and_more'),
        ('laboratory', '0002_laborder_visit_labtoken_laborder_lab_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField(default=datetime.date.today)),
                ('lab_token_number', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent'), ('STAT', 'Stat')], default='ROUTINE', max_length=20)),
                ('status', models.CharField(choices=[('ORDERED', 'Ordered'), ('SAMPLE_COLLECTED', 'Sample Collected'), ('RECEIVED_IN_LAB', 'Received In Lab'), ('IN_TESTING', 'In Testing'), ('RESULT_ENTERED', 'Result Entered'), ('VERIFIED', 'Verified'), ('AMENDED', 'Amended'), ('CANCELLED', 'Cancelled')], default='ORDERED', max_length=30)),
                ('clinical_indication', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='diagnostic_orders', to='facilities.facility')),
                ('ordering_doctor_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='ordered_diagnostics', to='accounts.staffprofile')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='diagnostic_orders', to='visits.visit')),
            ],
            options={
                'db_table': 'diagnostic_orders',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value_text', models.CharField(blank=True, default='', max_length=255)),
                ('result_value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('reference_range_applied', models.CharField(max_length=100)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('is_critical_panic', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ENTERED', 'Entered'), ('VERIFIED', 'Verified'), ('AMENDED', 'Amended')], default='ENTERED', max_length=20)),
                ('entered_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('entered_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='entered_diagnostic_results', to='accounts.staffprofile')),
            ],
            options={
                'db_table': 'diagnostic_results',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTestMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.CharField(max_length=50, unique=True)),
                ('test_name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=50)),
                ('specimen_type', models.CharField(max_length=50)),
                ('default_unit', models.CharField(blank=True, default='', max_length=30)),
                ('reference_range_male', models.CharField(blank=True, default='', max_length=100)),
                ('reference_range_female', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'diagnostic_test_masters',
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode_identifier', models.CharField(max_length=50, unique=True)),
                ('specimen_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COLLECTED', 'Collected'), ('RECEIVED', 'Received'), ('REJECTED', 'Rejected')], default='COLLECTED', max_length=20)),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('collected_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='collected_specimens', to='accounts.staffprofile')),
                ('diagnostic_order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='specimens', to='laboratory.diagnosticorder')),
            ],
            options={
                'db_table': 'specimens',
            },
        ),
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TESTING', 'In Testing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnostic_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_requests', to='laboratory.diagnosticorder')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='test_requests', to='laboratory.specimen')),
                ('test_master', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='test_requests', to='laboratory.diagnostictestmaster')),
            ],
            options={
                'db_table': 'test_requests',
                'unique_together': {('diagnostic_order', 'test_master')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosticResultAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_value_text', models.CharField(blank=True, default='', max_length=255)),
                ('previous_value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('amended_value_text', models.CharField(blank=True, default='', max_length=255)),
                ('amended_value_numeric', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('amendment_reason', models.TextField()),
                ('amended_at', models.DateTimeField(auto_now_add=True)),
                ('amended_by_staff', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='amended_diagnostic_results', to='accounts.staffprofile')),
                ('diagnostic_result', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='amendments', to='laboratory.diagnosticresult')),
            ],
            options={
                'db_table': 'diagnostic_result_amendments',
            },
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='test_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='diagnostic_result', to='laboratory.testrequest'),
        ),
        migrations.AddField(
            model_name='diagnosticresult',
            name='verified_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='verified_diagnostic_results', to='accounts.staffprofile'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticresult',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('status', 'VERIFIED'), ('verified_at__isnull', False), ('verified_by_staff__isnull', False)), models.Q(('status', 'VERIFIED'), _negated=True), _connector='OR'), name='chk_results_verification'),
        ),
    ]
