# Generated by Django 4.2.30 on 2026-09-23 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_diagnosticorder_diagnosticresult_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='diagnosticorder',
            index=models.Index(fields=['facility', 'order_date', 'lab_token_number'], name='idx_diag_order_token'),
        ),
        migrations.AddConstraint(
            model_name='diagnosticorder',
            constraint=models.UniqueConstraint(condition=models.Q(('lab_token_number__isnull', False)), fields=('facility', 'order_date', 'lab_token_number'), name='unique_facility_lab_order_token'),
        ),
    ]
